# Generated by Django 6.0.6 on 2026-06-12 23:30

import django.db.models.deletion
import leads.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='imię i nazwisko')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('phone', models.CharField(blank=True, max_length=64, verbose_name='telefon')),
                ('company', models.CharField(blank=True, max_length=180, verbose_name='firma')),
                ('inquiry_type', models.CharField(choices=[('b2b_components', 'Elementy drewniane B2B'), ('construction_joinery', 'Stolarka budowlana'), ('custom_artistic', 'Custom / stolarstwo artystyczne'), ('other', 'Inne')], max_length=64, verbose_name='typ zapytania')),
                ('scale', models.CharField(choices=[('one_piece', '1 sztuka'), ('small_series', 'Mała seria'), ('recurring', 'Stała współpraca'), ('unknown', 'Nie wiem jeszcze')], max_length=64, verbose_name='skala')),
                ('location', models.CharField(blank=True, max_length=180, verbose_name='lokalizacja')),
                ('expected_timing', models.CharField(blank=True, max_length=180, verbose_name='oczekiwany termin')),
                ('message', models.TextField(verbose_name='opis projektu')),
                ('consent', models.BooleanField(default=False, verbose_name='zgoda kontaktowa')),
                ('language', models.CharField(blank=True, max_length=16, verbose_name='język')),
                ('source_path', models.CharField(blank=True, max_length=255, verbose_name='źródłowy URL')),
                ('user_agent', models.TextField(blank=True, verbose_name='user agent')),
                ('is_handled', models.BooleanField(default=False, verbose_name='obsłużone')),
                ('admin_notes', models.TextField(blank=True, verbose_name='notatki')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='utworzono')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='zaktualizowano')),
            ],
            options={
                'verbose_name': 'zapytanie ofertowe',
                'verbose_name_plural': 'zapytania ofertowe',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuoteAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=leads.models.quote_attachment_path, verbose_name='plik')),
                ('original_name', models.CharField(max_length=255, verbose_name='oryginalna nazwa')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='dodano')),
                ('quote_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='leads.quoterequest', verbose_name='zapytanie')),
            ],
            options={
                'verbose_name': 'załącznik zapytania',
                'verbose_name_plural': 'załączniki zapytań',
            },
        ),
    ]
