# Generated by Django 6.0.6 on 2026-06-13 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quoterequest',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='scale',
            field=models.CharField(blank=True, choices=[('one_piece', '1 sztuka'), ('small_series', 'Mała seria'), ('recurring', 'Stała współpraca'), ('unknown', 'Nie wiem jeszcze')], default='unknown', max_length=64, verbose_name='skala'),
        ),
    ]
