# Generated by Django 6.0.6 on 2026-06-18 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_alter_quoterequest_email_alter_quoterequest_scale'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoterequest',
            name='central_lead_id',
            field=models.CharField(blank=True, max_length=80, verbose_name='centralny ID leada'),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='central_sync_last_error',
            field=models.TextField(blank=True, verbose_name='ostatni błąd synchronizacji centralnej'),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='central_sync_status',
            field=models.CharField(blank=True, max_length=40, verbose_name='status synchronizacji centralnej'),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='central_synced_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='zsynchronizowano centralnie'),
        ),
    ]
