UI_COPY = {
    "pl": {
        "skip_link": "Przejdź do treści",
        "nav_aria": "Główna nawigacja",
        "language_aria": "Wybór języka",
        "mobile_actions_aria": "Szybki kontakt",
        "mobile_call": "Zadzwoń",
        "mobile_quote": "Wycena",
        "brand_tagline": "stolarnia z Gościcina",
        "footer_contact": "Kontakt",
        "footer_quote": "Zapytanie",
        "footer_about": "Rodzinna stolarnia z Gościcina. Robimy elementy z drewna dla firm, stolarkę do domów i lokali oraz detale pod konkretny projekt.",
        "footer_quote_body": "Wyślij zdjęcie, rysunek albo krótki opis. Odpowiemy, czy temat pasuje do warsztatu i czego potrzeba do wyceny.",
        "footer_quote_link": "Wyślij zapytanie",
        "footer_guide_link": "Jak opisać zlecenie",
        "trust_aria": "Najważniejsze wyróżniki",
        "trust_region": "elementy dla firm",
        "trust_series": "próbka przed większą partią",
        "trust_specs": "montaż lokalnie w Pomorskiem",
        "trust_custom": "od zdjęcia, rysunku albo wzoru",
        "home_paths_eyebrow": "Oferta",
        "home_paths_title": "Wybierz temat, który pasuje do zlecenia",
        "home_b2b_eyebrow": "Dla firm",
        "home_b2b_title": "Drewniane elementy dla firm bez własnej stolarni",
        "home_b2b_body": "Jeśli potrzebujesz detalu do produktu, ekspozycji, mebla albo dalszego montażu, możemy zacząć od próbki i dopracować wykonanie przed kolejnymi partiami.",
        "home_b2b_item_photo": "praca od zdjęcia, wzoru, rysunku lub specyfikacji",
        "home_b2b_item_series": "próbka albo mała partia przed większym zamówieniem",
        "home_b2b_item_coop": "powtarzalne elementy dla producentów, agencji i wykonawców",
        "home_b2b_item_shipping": "pakowanie, odbiór lub wysyłka po ustaleniu elementu",
        "home_b2b_cta": "Zobacz produkcję dla firm",
        "home_b2b_image_alt": "Seria drewnianych elementów ułożona na stole warsztatowym",
        "process_eyebrow": "Od zapytania do decyzji",
        "process_title": "Jak zaczynamy zlecenie",
        "process_guide_cta": "Sprawdź checklistę",
        "portfolio_eyebrow": "Przykłady",
        "portfolio_title": "Najczęściej trafiają do nas takie tematy",
        "portfolio_cta": "Zobacz realizacje",
        "cta_eyebrow": "Masz coś do wykonania z drewna?",
        "cta_title": "Wyślij zdjęcie, rysunek albo wzór. Powiemy, czy możemy to zrobić.",
        "cta_button": "Wyślij zapytanie",
        "service_section_eyebrow": "Temat",
        "faq_eyebrow": "FAQ",
        "faq_title": "Najczęstsze pytania przed pierwszą rozmową",
        "quote_eyebrow": "Wycena",
        "quote_cta_title": "Masz zdjęcie, rysunek albo wzór? Wyślij go do oceny.",
        "quote_cta_button": "Wyślij zapytanie",
        "realizations_eyebrow": "Realizacje",
        "realizations_similar_cta": "Zapytaj o podobny temat",
        "quote_submit": "Wyślij zapytanie",
        "quote_quick_hint": "Wystarczy kilka zdań. Napisz, co ma powstać, i zostaw telefon albo email, żebyśmy mogli wrócić z konkretnymi pytaniami.",
        "quote_more_summary": "Mam więcej danych",
        "quote_more_hint": "Tu możesz dodać firmę, liczbę sztuk, lokalizację, termin albo pliki, jeśli masz je pod ręką.",
        "quote_aside_title": "Co przyspiesza odpowiedź?",
        "quote_aside_photo": "zdjęcie, rysunek, wzór lub podobny przykład",
        "quote_aside_dimensions": "wymiary albo orientacyjny rozmiar",
        "quote_aside_quantity": "liczba sztuk, próbka lub planowana seria",
        "quote_aside_material": "materiał, kolor albo oczekiwane wykończenie",
        "quote_aside_timing": "termin, miejscowość i sposób odbioru",
        "quote_aside_note": "Dla firm możemy rozmawiać o wysyłce poza Pomorskie. Pakowanie i transport oceniamy dopiero po poznaniu wymiarów oraz materiału.",
        "quote_guide_link": "Jak opisać zlecenie",
        "guide_slowdown_eyebrow": "Warto wiedzieć",
        "contact_eyebrow": "Kajax Stolarstwo",
        "contact_data": "Dane kontaktowe",
        "contact_address": "Adres",
        "contact_phone": "Telefon",
        "contact_email": "Email",
        "contact_best_path": "Najlepszy start to zdjęcie, rysunek albo wzór",
        "contact_best_path_body": "Zamiast opisywać wszystko od zera, pokaż element lub miejsce. Szybciej ocenimy, czy temat pasuje do warsztatu i czego brakuje do wyceny.",
        "contact_project_cta": "Wyślij zapytanie",
    },
    "en": {
        "skip_link": "Skip to content",
        "nav_aria": "Main navigation",
        "language_aria": "Language selection",
        "mobile_actions_aria": "Quick contact",
        "mobile_call": "Call",
        "mobile_quote": "Quote",
        "brand_tagline": "joinery workshop in Gościcino",
        "footer_contact": "Contact",
        "footer_quote": "Quote request",
        "footer_about": "A Gościcino joinery workshop for companies, architects and investors who need wooden elements made properly, technically and without vague promises.",
        "footer_quote_body": "The best starting point is a photo, drawing or specification. We will ask about material, quantity, timing, finish and logistics.",
        "footer_quote_link": "Go to the quote form",
        "footer_guide_link": "How to prepare an inquiry",
        "trust_aria": "Key strengths",
        "trust_region": "Pomerania",
        "trust_series": "short series",
        "trust_specs": "drawings and specifications",
        "trust_custom": "stairs, doors and details",
        "home_paths_eyebrow": "Offer",
        "home_paths_title": "What you can send us",
        "home_b2b_eyebrow": "For companies",
        "home_b2b_title": "Do you need repeatable wooden components?",
        "home_b2b_body": "We can prepare a prototype, a short run or repeatable components based on a sample. This fits companies that need wooden semi-finished parts, POS details or components for further assembly without building their own joinery operation.",
        "home_b2b_item_photo": "components based on a photo or drawing",
        "home_b2b_item_series": "trial runs and short batches",
        "home_b2b_item_coop": "recurring cooperation after the process is aligned",
        "home_b2b_item_shipping": "packing and shipping agreed individually",
        "home_b2b_cta": "Ask about component production",
        "home_b2b_image_alt": "Wooden profiles and trims as an example of repeatable components",
        "process_eyebrow": "How we start",
        "process_title": "From a photo or drawing to a concrete conversation",
        "process_guide_cta": "See the quote checklist",
        "portfolio_eyebrow": "Realizations",
        "portfolio_title": "Examples of topics worth sending for assessment",
        "portfolio_cta": "View realizations",
        "cta_eyebrow": "Do you have a photo, drawing or specification?",
        "cta_title": "Send the topic and we will tell you what comes next.",
        "cta_button": "Send for quote",
        "service_section_eyebrow": "Scope",
        "faq_eyebrow": "FAQ",
        "faq_title": "Common questions before a quote",
        "quote_eyebrow": "Quote",
        "quote_cta_title": "Send a photo, drawing or description. We will quickly clarify what is missing for pricing.",
        "quote_cta_button": "Go to form",
        "realizations_eyebrow": "Realizations",
        "realizations_similar_cta": "Ask about a similar project",
        "quote_submit": "Send inquiry",
        "quote_quick_hint": "Briefly describe the component, batch or joinery project and leave a phone number or email. A few concrete sentences are enough to start.",
        "quote_more_summary": "More information",
        "quote_more_hint": "Optionally add company, scale, location, timing or files. It speeds up assessment, but it does not block sending the inquiry.",
        "quote_aside_title": "What should you include?",
        "quote_aside_photo": "photo or drawing of the component",
        "quote_aside_dimensions": "approximate dimensions",
        "quote_aside_quantity": "quantity: one piece, sample, batch or recurring cooperation",
        "quote_aside_material": "material and expected finish",
        "quote_aside_timing": "timing and country/city of the project",
        "quote_aside_note": "For B2B projects we can discuss cooperation in Poland and Europe. Logistics, packing and shipping are agreed only after we understand the component.",
        "quote_guide_link": "Not sure what to prepare? See the checklist",
        "guide_slowdown_eyebrow": "Worth knowing",
        "contact_eyebrow": "Kajax Joinery",
        "contact_data": "Contact details",
        "contact_address": "Address",
        "contact_phone": "Phone",
        "contact_email": "Email",
        "contact_best_path": "Best path to a quote",
        "contact_best_path_body": "Send the form with a description, photo or drawing. It helps us assess whether the topic fits the workshop, what the risks are and what information is still missing.",
        "contact_project_cta": "Send project",
    },
    "de": {
        "skip_link": "Zum Inhalt springen",
        "nav_aria": "Hauptnavigation",
        "language_aria": "Sprachauswahl",
        "mobile_actions_aria": "Schneller Kontakt",
        "mobile_call": "Anrufen",
        "mobile_quote": "Anfrage",
        "brand_tagline": "Tischlerei in Gościcino",
        "footer_contact": "Kontakt",
        "footer_quote": "Anfrage",
        "footer_about": "Eine Tischlerei aus Gościcino für Unternehmen, Architekten und Investoren, die Holzelemente sauber, technisch sinnvoll und ohne vage Versprechen benötigen.",
        "footer_quote_body": "Am besten senden Sie ein Foto, eine Zeichnung oder eine Spezifikation. Wir fragen nach Material, Menge, Termin, Oberfläche und Logistik.",
        "footer_quote_link": "Zum Anfrageformular",
        "footer_guide_link": "Anfrage vorbereiten",
        "trust_aria": "Wichtigste Stärken",
        "trust_region": "Pommern",
        "trust_series": "Kleinserien",
        "trust_specs": "Zeichnungen und Spezifikationen",
        "trust_custom": "Sonderanfertigungen und Bauschreinerei",
        "home_paths_eyebrow": "Angebot",
        "home_paths_title": "Womit Sie sich an uns wenden können",
        "home_b2b_eyebrow": "Für Unternehmen",
        "home_b2b_title": "Benötigen Sie wiederholbare Holzelemente?",
        "home_b2b_body": "Wir können einen Prototyp, eine Kleinserie oder wiederholbare Elemente nach Muster vorbereiten. Das passt zu Firmen, die Holz-Halbzeuge, POS-Details oder Teile zur weiteren Montage brauchen, ohne eigene Tischlereikapazität aufzubauen.",
        "home_b2b_item_photo": "Elemente nach Foto oder Zeichnung",
        "home_b2b_item_series": "Probeläufe und Kleinserien",
        "home_b2b_item_coop": "regelmäßige Zusammenarbeit nach Prozessabstimmung",
        "home_b2b_item_shipping": "Verpackung und Versand individuell zu klären",
        "home_b2b_cta": "Elementproduktion anfragen",
        "home_b2b_image_alt": "Holzprofile und Leisten als Beispiel wiederholbarer Elemente",
        "process_eyebrow": "So starten wir",
        "process_title": "Vom Foto oder der Zeichnung zum konkreten Gespräch",
        "process_guide_cta": "Checkliste zur Anfrage ansehen",
        "portfolio_eyebrow": "Referenzen",
        "portfolio_title": "Beispiele für Themen, die sich zur Prüfung lohnen",
        "portfolio_cta": "Referenzen ansehen",
        "cta_eyebrow": "Haben Sie ein Foto, eine Zeichnung oder Spezifikation?",
        "cta_title": "Senden Sie das Thema. Wir sagen, was der nächste Schritt ist.",
        "cta_button": "Zur Anfrage senden",
        "service_section_eyebrow": "Umfang",
        "faq_eyebrow": "FAQ",
        "faq_title": "Häufige Fragen vor der Anfrage",
        "quote_eyebrow": "Anfrage",
        "quote_cta_title": "Senden Sie Foto, Zeichnung oder Beschreibung. Wir klären schnell, was für die Anfrage noch fehlt.",
        "quote_cta_button": "Zum Formular",
        "realizations_eyebrow": "Referenzen",
        "realizations_similar_cta": "Ähnliches Projekt anfragen",
        "quote_submit": "Anfrage senden",
        "quote_quick_hint": "Beschreiben Sie kurz Element, Serie oder Schreinerarbeit und hinterlassen Sie Telefon oder E-Mail. Einige konkrete Sätze reichen für den Start.",
        "quote_more_summary": "Weitere Informationen",
        "quote_more_hint": "Optional können Sie Firma, Umfang, Standort, Zeitrahmen oder Dateien ergänzen. Das beschleunigt die Einschätzung, blockiert die Anfrage aber nicht.",
        "quote_aside_title": "Was sollte enthalten sein?",
        "quote_aside_photo": "Foto oder Zeichnung des Elements",
        "quote_aside_dimensions": "ungefähre Maße",
        "quote_aside_quantity": "Menge: Einzelstück, Muster, Serie oder regelmäßige Zusammenarbeit",
        "quote_aside_material": "Material und gewünschte Oberfläche",
        "quote_aside_timing": "Termin sowie Land/Stadt des Projekts",
        "quote_aside_note": "Für B2B-Projekte können wir über Zusammenarbeit in Polen und Europa sprechen. Logistik, Verpackung und Versand werden erst nach Prüfung des Elements festgelegt.",
        "quote_guide_link": "Nicht sicher, was Sie vorbereiten sollen? Zur Checkliste",
        "guide_slowdown_eyebrow": "Gut zu wissen",
        "contact_eyebrow": "Kajax Tischlerei",
        "contact_data": "Kontaktdaten",
        "contact_address": "Adresse",
        "contact_phone": "Telefon",
        "contact_email": "E-Mail",
        "contact_best_path": "Der beste Weg zur Anfrage",
        "contact_best_path_body": "Senden Sie das Formular mit Beschreibung, Foto oder Zeichnung. So können wir schneller prüfen, ob das Thema zur Werkstatt passt, welche Risiken bestehen und welche Informationen fehlen.",
        "contact_project_cta": "Projekt senden",
    },
    "sv": {
        "skip_link": "Hoppa till innehåll",
        "nav_aria": "Huvudnavigering",
        "language_aria": "Språkval",
        "mobile_actions_aria": "Snabb kontakt",
        "mobile_call": "Ring",
        "mobile_quote": "Offert",
        "brand_tagline": "snickeri i Gościcino",
        "footer_contact": "Kontakt",
        "footer_quote": "Offertförfrågan",
        "footer_about": "Ett snickeri från Gościcino för företag, arkitekter och investerare som behöver träkomponenter utförda noggrant, tekniskt genomtänkt och utan vaga löften.",
        "footer_quote_body": "Börja gärna med ett foto, en ritning eller en specifikation. Vi frågar om material, antal, tidplan, finish och logistik.",
        "footer_quote_link": "Gå till offertformuläret",
        "footer_guide_link": "Så förbereder du en förfrågan",
        "trust_aria": "Viktigaste styrkor",
        "trust_region": "Pommern",
        "trust_series": "korta serier",
        "trust_specs": "ritningar och specifikationer",
        "trust_custom": "special- och byggsnickeri",
        "home_paths_eyebrow": "Erbjudande",
        "home_paths_title": "Vad du kan skicka till oss",
        "home_b2b_eyebrow": "För företag",
        "home_b2b_title": "Behöver du återkommande träkomponenter?",
        "home_b2b_body": "Vi kan ta fram en prototyp, en kort serie eller återkommande komponenter efter prov. Det passar företag som behöver halvfabrikat i trä, POS-detaljer eller komponenter för vidare montage utan att bygga eget snickeri.",
        "home_b2b_item_photo": "komponenter efter foto eller ritning",
        "home_b2b_item_series": "prover och korta serier",
        "home_b2b_item_coop": "återkommande samarbete efter processanpassning",
        "home_b2b_item_shipping": "packning och frakt avtalas individuellt",
        "home_b2b_cta": "Fråga om komponentproduktion",
        "home_b2b_image_alt": "Träprofiler och lister som exempel på återkommande komponenter",
        "process_eyebrow": "Så börjar vi",
        "process_title": "Från foto eller ritning till konkret dialog",
        "process_guide_cta": "Se checklistan för offert",
        "portfolio_eyebrow": "Referenser",
        "portfolio_title": "Exempel på uppdrag som är värda att skicka för bedömning",
        "portfolio_cta": "Visa referenser",
        "cta_eyebrow": "Har du ett foto, en ritning eller specifikation?",
        "cta_title": "Skicka ämnet. Vi säger vad nästa steg är.",
        "cta_button": "Skicka för offert",
        "service_section_eyebrow": "Omfattning",
        "faq_eyebrow": "FAQ",
        "faq_title": "Vanliga frågor inför offert",
        "quote_eyebrow": "Offert",
        "quote_cta_title": "Skicka foto, ritning eller beskrivning. Vi klargör snabbt vad som saknas för offert.",
        "quote_cta_button": "Gå till formulär",
        "realizations_eyebrow": "Referenser",
        "realizations_similar_cta": "Fråga om liknande projekt",
        "quote_submit": "Skicka förfrågan",
        "quote_quick_hint": "Beskriv kort komponenten, serien eller snickeriet och lämna telefon eller e-post. Några konkreta meningar räcker för start.",
        "quote_more_summary": "Mer information",
        "quote_more_hint": "Lägg gärna till företag, omfattning, plats, tidplan eller filer. Det snabbar upp bedömningen men stoppar inte förfrågan.",
        "quote_aside_title": "Vad bör du bifoga?",
        "quote_aside_photo": "foto eller ritning av komponenten",
        "quote_aside_dimensions": "ungefärliga mått",
        "quote_aside_quantity": "antal: enstaka del, prov, serie eller återkommande samarbete",
        "quote_aside_material": "material och önskad ytbehandling",
        "quote_aside_timing": "tidplan och projektets land/stad",
        "quote_aside_note": "För B2B kan vi diskutera samarbete i Polen och Europa. Logistik, packning och frakt bestäms först när vi förstått komponenten.",
        "quote_guide_link": "Osäker på vad du ska förbereda? Se checklistan",
        "guide_slowdown_eyebrow": "Bra att veta",
        "contact_eyebrow": "Kajax Snickeri",
        "contact_data": "Kontaktuppgifter",
        "contact_address": "Adress",
        "contact_phone": "Telefon",
        "contact_email": "E-post",
        "contact_best_path": "Bästa vägen till offert",
        "contact_best_path_body": "Skicka formuläret med beskrivning, foto eller ritning. Då kan vi snabbare bedöma om uppdraget passar verkstaden, vilka risker som finns och vad som saknas.",
        "contact_project_cta": "Skicka projekt",
    },
    "da": {
        "skip_link": "Gå til indhold",
        "nav_aria": "Hovednavigation",
        "language_aria": "Sprogvalg",
        "mobile_actions_aria": "Hurtig kontakt",
        "mobile_call": "Ring",
        "mobile_quote": "Tilbud",
        "brand_tagline": "snedkeri i Gościcino",
        "footer_contact": "Kontakt",
        "footer_quote": "Tilbudsanmodning",
        "footer_about": "Et snedkeri fra Gościcino for virksomheder, arkitekter og investorer, der har brug for trækomponenter udført solidt, teknisk gennemtænkt og uden uklare løfter.",
        "footer_quote_body": "Start gerne med et foto, en tegning eller en specifikation. Vi spørger ind til materiale, antal, tidsplan, finish og logistik.",
        "footer_quote_link": "Gå til tilbudsformularen",
        "footer_guide_link": "Sådan forbereder du en forespørgsel",
        "trust_aria": "Vigtigste styrker",
        "trust_region": "Pommern",
        "trust_series": "korte serier",
        "trust_specs": "tegninger og specifikationer",
        "trust_custom": "special- og byggesnedkeri",
        "home_paths_eyebrow": "Tilbud",
        "home_paths_title": "Hvad du kan sende til os",
        "home_b2b_eyebrow": "For virksomheder",
        "home_b2b_title": "Har du brug for gentagelige trækomponenter?",
        "home_b2b_body": "Vi kan fremstille en prototype, en kort serie eller gentagelige komponenter efter prøve. Det passer til virksomheder, der har brug for halvfabrikata i træ, POS-detaljer eller komponenter til videre montage uden at opbygge eget snedkeri.",
        "home_b2b_item_photo": "komponenter efter foto eller tegning",
        "home_b2b_item_series": "prøver og korte serier",
        "home_b2b_item_coop": "løbende samarbejde efter procesafstemning",
        "home_b2b_item_shipping": "pakning og forsendelse aftales individuelt",
        "home_b2b_cta": "Spørg om komponentproduktion",
        "home_b2b_image_alt": "Træprofiler og lister som eksempel på gentagelige komponenter",
        "process_eyebrow": "Sådan starter vi",
        "process_title": "Fra foto eller tegning til konkret dialog",
        "process_guide_cta": "Se checklisten til tilbud",
        "portfolio_eyebrow": "Referencer",
        "portfolio_title": "Eksempler på opgaver der er værd at sende til vurdering",
        "portfolio_cta": "Se referencer",
        "cta_eyebrow": "Har du et foto, en tegning eller specifikation?",
        "cta_title": "Send emnet. Vi siger, hvad næste skridt er.",
        "cta_button": "Send til tilbud",
        "service_section_eyebrow": "Omfang",
        "faq_eyebrow": "FAQ",
        "faq_title": "Typiske spørgsmål før tilbud",
        "quote_eyebrow": "Tilbud",
        "quote_cta_title": "Send foto, tegning eller beskrivelse. Vi afklarer hurtigt, hvad der mangler til tilbud.",
        "quote_cta_button": "Gå til formular",
        "realizations_eyebrow": "Referencer",
        "realizations_similar_cta": "Spørg om et lignende projekt",
        "quote_submit": "Send forespørgsel",
        "quote_quick_hint": "Beskriv kort komponenten, serien eller snedkerarbejdet og angiv telefon eller e-mail. Få konkrete sætninger er nok til start.",
        "quote_more_summary": "Flere oplysninger",
        "quote_more_hint": "Tilføj eventuelt virksomhed, omfang, placering, tidsplan eller filer. Det gør vurderingen hurtigere, men stopper ikke forespørgslen.",
        "quote_aside_title": "Hvad bør du vedhæfte?",
        "quote_aside_photo": "foto eller tegning af komponenten",
        "quote_aside_dimensions": "omtrentlige mål",
        "quote_aside_quantity": "antal: én del, prøve, serie eller løbende samarbejde",
        "quote_aside_material": "materiale og ønsket finish",
        "quote_aside_timing": "tidsplan og projektets land/by",
        "quote_aside_note": "For B2B kan vi tale om samarbejde i Polen og Europa. Logistik, pakning og forsendelse aftales først, når vi kender komponenten.",
        "quote_guide_link": "Ikke sikker på hvad du skal forberede? Se checklisten",
        "guide_slowdown_eyebrow": "Værd at vide",
        "contact_eyebrow": "Kajax Snedkeri",
        "contact_data": "Kontaktoplysninger",
        "contact_address": "Adresse",
        "contact_phone": "Telefon",
        "contact_email": "E-mail",
        "contact_best_path": "Bedste vej til tilbud",
        "contact_best_path_body": "Send formularen med beskrivelse, foto eller tegning. Det gør det hurtigere at vurdere, om opgaven passer til værkstedet, hvilke risici der er, og hvilke oplysninger der mangler.",
        "contact_project_cta": "Send projekt",
    },
    "no": {
        "skip_link": "Gå til innhold",
        "nav_aria": "Hovednavigasjon",
        "language_aria": "Språkvalg",
        "mobile_actions_aria": "Rask kontakt",
        "mobile_call": "Ring",
        "mobile_quote": "Forespørsel",
        "brand_tagline": "snekkerverksted i Gościcino",
        "footer_contact": "Kontakt",
        "footer_quote": "Forespørsel",
        "footer_about": "Et snekkerverksted fra Gościcino for bedrifter, arkitekter og investorer som trenger trekomponenter utført grundig, teknisk gjennomtenkt og uten uklare løfter.",
        "footer_quote_body": "Start gjerne med et bilde, en tegning eller en spesifikasjon. Vi spør om materiale, antall, tidsplan, overflate og logistikk.",
        "footer_quote_link": "Gå til forespørselsskjemaet",
        "footer_guide_link": "Slik forbereder du en forespørsel",
        "trust_aria": "Viktigste styrker",
        "trust_region": "Pommern",
        "trust_series": "korte serier",
        "trust_specs": "tegninger og spesifikasjoner",
        "trust_custom": "spesial- og byggsnekkerarbeid",
        "home_paths_eyebrow": "Tilbud",
        "home_paths_title": "Hva du kan sende til oss",
        "home_b2b_eyebrow": "For bedrifter",
        "home_b2b_title": "Trenger du repeterbare trekomponenter?",
        "home_b2b_body": "Vi kan lage en prototype, en kort serie eller repeterbare komponenter basert på prøve. Det passer for bedrifter som trenger halvfabrikata i tre, POS-detaljer eller komponenter for videre montering uten å bygge eget snekkerverksted.",
        "home_b2b_item_photo": "komponenter etter bilde eller tegning",
        "home_b2b_item_series": "prøver og korte serier",
        "home_b2b_item_coop": "fast samarbeid etter at prosessen er avklart",
        "home_b2b_item_shipping": "pakking og frakt avtales individuelt",
        "home_b2b_cta": "Spør om komponentproduksjon",
        "home_b2b_image_alt": "Treprofiler og lister som eksempel på repeterbare komponenter",
        "process_eyebrow": "Slik starter vi",
        "process_title": "Fra bilde eller tegning til konkret dialog",
        "process_guide_cta": "Se sjekklisten for forespørsel",
        "portfolio_eyebrow": "Referanser",
        "portfolio_title": "Eksempler på oppdrag som er verdt å sende til vurdering",
        "portfolio_cta": "Se referanser",
        "cta_eyebrow": "Har du et bilde, en tegning eller spesifikasjon?",
        "cta_title": "Send temaet. Vi sier hva neste steg er.",
        "cta_button": "Send til vurdering",
        "service_section_eyebrow": "Omfang",
        "faq_eyebrow": "FAQ",
        "faq_title": "Vanlige spørsmål før forespørsel",
        "quote_eyebrow": "Forespørsel",
        "quote_cta_title": "Send bilde, tegning eller beskrivelse. Vi avklarer raskt hva som mangler for pris.",
        "quote_cta_button": "Gå til skjema",
        "realizations_eyebrow": "Referanser",
        "realizations_similar_cta": "Spør om et lignende prosjekt",
        "quote_submit": "Send forespørsel",
        "quote_quick_hint": "Beskriv kort komponenten, serien eller snekkerarbeidet og legg igjen telefon eller e-post. Noen konkrete setninger er nok for start.",
        "quote_more_summary": "Mer informasjon",
        "quote_more_hint": "Legg gjerne til firma, omfang, sted, tidsplan eller filer. Det gjør vurderingen raskere, men stopper ikke forespørselen.",
        "quote_aside_title": "Hva bør du legge ved?",
        "quote_aside_photo": "bilde eller tegning av komponenten",
        "quote_aside_dimensions": "omtrentlige mål",
        "quote_aside_quantity": "antall: én del, prøve, serie eller fast samarbeid",
        "quote_aside_material": "materiale og ønsket finish",
        "quote_aside_timing": "tidsplan og prosjektets land/by",
        "quote_aside_note": "For B2B kan vi diskutere samarbeid i Polen og Europa. Logistikk, pakking og frakt avtales først når vi forstår komponenten.",
        "quote_guide_link": "Usikker på hva du skal forberede? Se sjekklisten",
        "guide_slowdown_eyebrow": "Verdt å vite",
        "contact_eyebrow": "Kajax Snekkerverksted",
        "contact_data": "Kontaktinformasjon",
        "contact_address": "Adresse",
        "contact_phone": "Telefon",
        "contact_email": "E-post",
        "contact_best_path": "Beste vei til vurdering",
        "contact_best_path_body": "Send skjemaet med beskrivelse, bilde eller tegning. Da kan vi raskere vurdere om oppdraget passer verkstedet, hvilke risikoer som finnes og hvilken informasjon som mangler.",
        "contact_project_cta": "Send prosjekt",
    },
}


_MENU_LABELS = {
    "pl": "Menu",
    "en": "Menu",
    "de": "Menü",
    "sv": "Meny",
    "da": "Menu",
    "no": "Meny",
}

_QUOTE_FILE_PROMPTS = {
    "pl": {
        "quote_file_prompt_strong": "Masz zdjęcie, rysunek albo wzór?",
        "quote_file_prompt": "Dodaj plik w sekcji „Mam więcej danych” albo opisz, co możesz dosłać później.",
    },
    "en": {
        "quote_file_prompt_strong": "Do you have a photo, drawing or sample?",
        "quote_file_prompt": "Add a file under “More information” or describe what you can send later.",
    },
    "de": {
        "quote_file_prompt_strong": "Haben Sie ein Foto, eine Zeichnung oder ein Muster?",
        "quote_file_prompt": "Fügen Sie die Datei unter „Weitere Informationen” hinzu oder beschreiben Sie, was Sie später senden können.",
    },
    "sv": {
        "quote_file_prompt_strong": "Har du ett foto, en ritning eller ett prov?",
        "quote_file_prompt": "Lägg till filen under ”Mer information” eller beskriv vad du kan skicka senare.",
    },
    "da": {
        "quote_file_prompt_strong": "Har du foto, tegning eller prøve?",
        "quote_file_prompt": "Tilføj filen under “Mere information” eller beskriv, hvad du kan sende senere.",
    },
    "no": {
        "quote_file_prompt_strong": "Har du bilde, tegning eller prøve?",
        "quote_file_prompt": "Legg til filen under «Mer informasjon» eller beskriv hva du kan sende senere.",
    },
}

for _code, _copy in UI_COPY.items():
    _copy.setdefault("menu_label", _MENU_LABELS.get(_code, "Menu"))
    _copy.update(_QUOTE_FILE_PROMPTS.get(_code, _QUOTE_FILE_PROMPTS["en"]))


def get_ui_copy(language_code):
    normalized = (language_code or "pl").split("-")[0]
    return UI_COPY.get(normalized, UI_COPY["pl"])
