UI_COPY = {
    "pl": {
        "skip_link": "Przejdź do treści",
        "nav_aria": "Główna nawigacja",
        "mobile_actions_aria": "Szybki kontakt",
        "mobile_call": "Zadzwoń",
        "mobile_quote": "Wycena",
        "brand_tagline": "stolarnia produkcyjno-budowlana",
        "footer_contact": "Kontakt",
        "footer_quote": "Zapytanie",
        "footer_about": "Stolarnia z Gościcina dla firm, architektów i inwestorów, którzy potrzebują drewna wykonanego porządnie i z sensem technicznym.",
        "footer_quote_body": "Najlepiej wyślij zdjęcie, rysunek albo specyfikację. Dopytamy o materiał, ilość, termin i logistykę.",
        "footer_quote_link": "Przejdź do formularza wyceny",
        "footer_guide_link": "Jak przygotować zapytanie",
        "trust_aria": "Najważniejsze wyróżniki",
        "trust_region": "Pomorskie",
        "trust_series": "krótkie serie",
        "trust_specs": "rysunki i specyfikacje",
        "trust_custom": "custom i stolarka budowlana",
        "home_paths_eyebrow": "Oferta",
        "home_paths_title": "Drewno do produkcji, wnętrz i projektów specjalnych",
        "home_b2b_eyebrow": "Kierunek B2B",
        "home_b2b_title": "Potrzebujesz powtarzalnych elementów drewnianych?",
        "home_b2b_body": "Możemy przygotować pojedynczy prototyp, krótką serię albo powtarzalne elementy według wzoru. To kierunek dla firm, które chcą mieć drewniane półprodukty lub detale bez budowania własnego zaplecza stolarskiego.",
        "home_b2b_item_photo": "elementy według zdjęcia lub rysunku",
        "home_b2b_item_series": "serie próbne i krótkie partie",
        "home_b2b_item_coop": "możliwość stałej współpracy po dopasowaniu procesu",
        "home_b2b_item_shipping": "pakowanie i wysyłka ustalane indywidualnie",
        "home_b2b_cta": "Zapytaj o produkcję elementów",
        "home_b2b_image_alt": "Drewniane profile i listwy jako przykład elementów wykonywanych powtarzalnie",
        "process_eyebrow": "Proces wyceny",
        "process_title": "Im lepszy materiał wejściowy, tym szybciej ocenimy projekt",
        "process_guide_cta": "Zobacz checklistę do wyceny",
        "portfolio_eyebrow": "Realizacje",
        "portfolio_title": "Wybrane kierunki prac, które najlepiej pokazują możliwości warsztatu",
        "portfolio_cta": "Zobacz realizacje",
        "cta_eyebrow": "Masz zdjęcie, rysunek albo specyfikację?",
        "cta_title": "Wyślij projekt. Ocenimy, czy możemy go wykonać.",
        "cta_button": "Wyślij do wyceny",
        "service_section_eyebrow": "Zakres",
        "faq_eyebrow": "FAQ",
        "faq_title": "Najczęstsze pytania przed wyceną",
        "quote_eyebrow": "Wycena",
        "quote_cta_title": "Wyślij zdjęcie, rysunek albo opis. Dopytamy o resztę.",
        "quote_cta_button": "Przejdź do formularza",
        "realizations_eyebrow": "Realizacje",
        "realizations_similar_cta": "Zapytaj o podobny projekt",
        "quote_submit": "Wyślij zapytanie",
        "quote_quick_hint": "Krótko opisz temat i zostaw telefon albo email. Resztę możemy doprecyzować później.",
        "quote_more_summary": "Więcej informacji",
        "quote_more_hint": "Opcjonalnie dodaj firmę, skalę, lokalizację, termin albo pliki. To pomaga szybciej ocenić projekt, ale nie jest wymagane.",
        "quote_aside_title": "Co warto dołączyć?",
        "quote_aside_photo": "zdjęcie lub rysunek elementu",
        "quote_aside_dimensions": "orientacyjne wymiary",
        "quote_aside_quantity": "ilość: 1 sztuka, próbka, seria lub stała współpraca",
        "quote_aside_material": "materiał i oczekiwane wykończenie",
        "quote_aside_timing": "termin oraz kraj/miasto realizacji",
        "quote_aside_note": "Dla B2B możemy rozmawiać o projektach europejskich. Logistykę, pakowanie i wysyłkę ustalamy po poznaniu elementu.",
        "quote_guide_link": "Nie wiesz, co przygotować? Zobacz checklistę",
        "guide_slowdown_eyebrow": "Warto wiedzieć",
        "contact_eyebrow": "Kajax Stolarstwo",
        "contact_data": "Dane kontaktowe",
        "contact_address": "Adres",
        "contact_phone": "Telefon",
        "contact_email": "Email",
        "contact_best_path": "Najlepsza droga do wyceny",
        "contact_best_path_body": "Wyślij formularz z opisem, zdjęciem albo rysunkiem. To pozwala szybciej ocenić, czy temat pasuje do warsztatu i jakich informacji jeszcze brakuje.",
        "contact_project_cta": "Wyślij projekt",
    },
    "en": {
        "skip_link": "Skip to content",
        "nav_aria": "Main navigation",
        "mobile_actions_aria": "Quick contact",
        "mobile_call": "Call",
        "mobile_quote": "Quote",
        "brand_tagline": "production and construction joinery workshop",
        "footer_contact": "Contact",
        "footer_quote": "Quote request",
        "footer_about": "A joinery workshop from Gościcino for companies, architects and investors who need woodwork made properly and with technical sense.",
        "footer_quote_body": "The best starting point is a photo, drawing or specification. We will ask about material, quantity, timing and logistics.",
        "footer_quote_link": "Go to the quote form",
        "footer_guide_link": "How to prepare an inquiry",
        "trust_aria": "Key strengths",
        "trust_region": "Pomerania",
        "trust_series": "short series",
        "trust_specs": "drawings and specifications",
        "trust_custom": "custom and construction joinery",
        "home_paths_eyebrow": "Offer",
        "home_paths_title": "Woodwork for production, interiors and special projects",
        "home_b2b_eyebrow": "B2B direction",
        "home_b2b_title": "Do you need repeatable wooden components?",
        "home_b2b_body": "We can prepare a single prototype, a short run or repeatable components based on a sample. This is useful for companies that need a reliable workshop without building their own small joinery operation.",
        "home_b2b_item_photo": "components based on a photo or drawing",
        "home_b2b_item_series": "trial runs and short batches",
        "home_b2b_item_coop": "recurring cooperation after the process is aligned",
        "home_b2b_item_shipping": "packing and shipping agreed individually",
        "home_b2b_cta": "Ask about component production",
        "home_b2b_image_alt": "Wooden profiles and trims as an example of repeatable components",
        "process_eyebrow": "Quote process",
        "process_title": "The better the input, the faster we can assess the project",
        "process_guide_cta": "See the quote checklist",
        "portfolio_eyebrow": "Realizations",
        "portfolio_title": "Selected work directions that show what the workshop can handle",
        "portfolio_cta": "View realizations",
        "cta_eyebrow": "Do you have a photo, drawing or specification?",
        "cta_title": "Send the project. We will assess whether we can make it.",
        "cta_button": "Send for quote",
        "service_section_eyebrow": "Scope",
        "faq_eyebrow": "FAQ",
        "faq_title": "Common questions before a quote",
        "quote_eyebrow": "Quote",
        "quote_cta_title": "Send a photo, drawing or description. We will ask for the rest.",
        "quote_cta_button": "Go to form",
        "realizations_eyebrow": "Realizations",
        "realizations_similar_cta": "Ask about a similar project",
        "quote_submit": "Send inquiry",
        "quote_quick_hint": "Briefly describe the topic and leave a phone number or email. We can clarify the rest later.",
        "quote_more_summary": "More information",
        "quote_more_hint": "Optionally add company, scale, location, timing or files. It helps us assess the project faster, but it is not required.",
        "quote_aside_title": "What should you include?",
        "quote_aside_photo": "photo or drawing of the component",
        "quote_aside_dimensions": "approximate dimensions",
        "quote_aside_quantity": "quantity: one piece, sample, batch or recurring cooperation",
        "quote_aside_material": "material and expected finish",
        "quote_aside_timing": "timing and country/city of the project",
        "quote_aside_note": "For B2B projects we can discuss European cooperation. Logistics, packing and shipping are agreed after we understand the component.",
        "quote_guide_link": "Not sure what to prepare? See the checklist",
        "guide_slowdown_eyebrow": "Worth knowing",
        "contact_eyebrow": "Kajax Joinery",
        "contact_data": "Contact details",
        "contact_address": "Address",
        "contact_phone": "Phone",
        "contact_email": "Email",
        "contact_best_path": "Best path to a quote",
        "contact_best_path_body": "Send the form with a description, photo or drawing. It helps us quickly assess whether the topic fits the workshop and what information is still missing.",
        "contact_project_cta": "Send project",
    },
    "de": {
        "skip_link": "Zum Inhalt springen",
        "nav_aria": "Hauptnavigation",
        "mobile_actions_aria": "Schneller Kontakt",
        "mobile_call": "Anrufen",
        "mobile_quote": "Anfrage",
        "brand_tagline": "Produktions- und Bauschreinerei",
        "footer_contact": "Kontakt",
        "footer_quote": "Anfrage",
        "footer_about": "Eine Tischlerei aus Gościcino für Unternehmen, Architekten und Investoren, die technisch sinnvoll gefertigte Holzelemente benötigen.",
        "footer_quote_body": "Am besten senden Sie ein Foto, eine Zeichnung oder eine Spezifikation. Wir fragen nach Material, Menge, Termin und Logistik.",
        "footer_quote_link": "Zum Anfrageformular",
        "footer_guide_link": "Anfrage vorbereiten",
        "trust_aria": "Wichtigste Stärken",
        "trust_region": "Pommern",
        "trust_series": "Kleinserien",
        "trust_specs": "Zeichnungen und Spezifikationen",
        "trust_custom": "Sonderanfertigungen und Bauschreinerei",
        "home_paths_eyebrow": "Angebot",
        "home_paths_title": "Holzarbeiten für Produktion, Innenräume und Sonderprojekte",
        "home_b2b_eyebrow": "B2B-Ausrichtung",
        "home_b2b_title": "Benötigen Sie wiederholbare Holzelemente?",
        "home_b2b_body": "Wir können einen Prototyp, eine Kleinserie oder wiederholbare Elemente nach Muster vorbereiten. Das passt zu Firmen, die eine zuverlässige Werkstatt brauchen, ohne eine eigene kleine Tischlerei aufzubauen.",
        "home_b2b_item_photo": "Elemente nach Foto oder Zeichnung",
        "home_b2b_item_series": "Probeläufe und Kleinserien",
        "home_b2b_item_coop": "regelmäßige Zusammenarbeit nach Prozessabstimmung",
        "home_b2b_item_shipping": "Verpackung und Versand individuell zu klären",
        "home_b2b_cta": "Elementproduktion anfragen",
        "home_b2b_image_alt": "Holzprofile und Leisten als Beispiel wiederholbarer Elemente",
        "process_eyebrow": "Anfrageprozess",
        "process_title": "Je besser die Unterlagen, desto schneller können wir das Projekt bewerten",
        "process_guide_cta": "Checkliste zur Anfrage ansehen",
        "portfolio_eyebrow": "Referenzen",
        "portfolio_title": "Ausgewählte Arbeitsbereiche, die die Möglichkeiten der Werkstatt zeigen",
        "portfolio_cta": "Referenzen ansehen",
        "cta_eyebrow": "Haben Sie ein Foto, eine Zeichnung oder Spezifikation?",
        "cta_title": "Senden Sie das Projekt. Wir prüfen, ob wir es umsetzen können.",
        "cta_button": "Zur Anfrage senden",
        "service_section_eyebrow": "Umfang",
        "faq_eyebrow": "FAQ",
        "faq_title": "Häufige Fragen vor der Anfrage",
        "quote_eyebrow": "Anfrage",
        "quote_cta_title": "Senden Sie ein Foto, eine Zeichnung oder Beschreibung. Den Rest klären wir nach.",
        "quote_cta_button": "Zum Formular",
        "realizations_eyebrow": "Referenzen",
        "realizations_similar_cta": "Ähnliches Projekt anfragen",
        "quote_submit": "Anfrage senden",
        "quote_quick_hint": "Beschreiben Sie das Thema kurz und hinterlassen Sie Telefon oder E-Mail. Den Rest können wir später klären.",
        "quote_more_summary": "Weitere Informationen",
        "quote_more_hint": "Optional können Sie Firma, Umfang, Standort, Zeitrahmen oder Dateien ergänzen. Das hilft bei der schnelleren Einschätzung, ist aber nicht zwingend.",
        "quote_aside_title": "Was sollte enthalten sein?",
        "quote_aside_photo": "Foto oder Zeichnung des Elements",
        "quote_aside_dimensions": "ungefähre Maße",
        "quote_aside_quantity": "Menge: Einzelstück, Muster, Serie oder regelmäßige Zusammenarbeit",
        "quote_aside_material": "Material und gewünschte Oberfläche",
        "quote_aside_timing": "Termin sowie Land/Stadt des Projekts",
        "quote_aside_note": "Für B2B-Projekte können wir über europäische Zusammenarbeit sprechen. Logistik, Verpackung und Versand werden nach Prüfung des Elements festgelegt.",
        "quote_guide_link": "Nicht sicher, was Sie vorbereiten sollen? Zur Checkliste",
        "guide_slowdown_eyebrow": "Gut zu wissen",
        "contact_eyebrow": "Kajax Tischlerei",
        "contact_data": "Kontaktdaten",
        "contact_address": "Adresse",
        "contact_phone": "Telefon",
        "contact_email": "E-Mail",
        "contact_best_path": "Der beste Weg zur Anfrage",
        "contact_best_path_body": "Senden Sie das Formular mit Beschreibung, Foto oder Zeichnung. So können wir schneller prüfen, ob das Thema zur Werkstatt passt und welche Informationen fehlen.",
        "contact_project_cta": "Projekt senden",
    },
    "sv": {
        "skip_link": "Hoppa till innehåll",
        "nav_aria": "Huvudnavigering",
        "mobile_actions_aria": "Snabb kontakt",
        "mobile_call": "Ring",
        "mobile_quote": "Offert",
        "brand_tagline": "produktions- och byggsnickeri",
        "footer_contact": "Kontakt",
        "footer_quote": "Offertförfrågan",
        "footer_about": "Ett snickeri från Gościcino för företag, arkitekter och investerare som behöver träarbete utfört noggrant och tekniskt genomtänkt.",
        "footer_quote_body": "Börja gärna med ett foto, en ritning eller en specifikation. Vi frågar om material, antal, tidplan och logistik.",
        "footer_quote_link": "Gå till offertformuläret",
        "footer_guide_link": "Så förbereder du en förfrågan",
        "trust_aria": "Viktigaste styrkor",
        "trust_region": "Pommern",
        "trust_series": "korta serier",
        "trust_specs": "ritningar och specifikationer",
        "trust_custom": "special- och byggsnickeri",
        "home_paths_eyebrow": "Erbjudande",
        "home_paths_title": "Träarbete för produktion, interiörer och specialprojekt",
        "home_b2b_eyebrow": "B2B-inriktning",
        "home_b2b_title": "Behöver du återkommande träkomponenter?",
        "home_b2b_body": "Vi kan ta fram en prototyp, en kort serie eller återkommande komponenter efter prov. Det passar företag som behöver en pålitlig verkstad utan att bygga ett eget litet snickeri.",
        "home_b2b_item_photo": "komponenter efter foto eller ritning",
        "home_b2b_item_series": "prover och korta serier",
        "home_b2b_item_coop": "återkommande samarbete efter processanpassning",
        "home_b2b_item_shipping": "packning och frakt avtalas individuellt",
        "home_b2b_cta": "Fråga om komponentproduktion",
        "home_b2b_image_alt": "Träprofiler och lister som exempel på återkommande komponenter",
        "process_eyebrow": "Offertprocess",
        "process_title": "Ju bättre underlag, desto snabbare kan vi bedöma projektet",
        "process_guide_cta": "Se checklistan för offert",
        "portfolio_eyebrow": "Referenser",
        "portfolio_title": "Utvalda arbetsområden som visar vad verkstaden kan hantera",
        "portfolio_cta": "Visa referenser",
        "cta_eyebrow": "Har du ett foto, en ritning eller specifikation?",
        "cta_title": "Skicka projektet. Vi bedömer om vi kan tillverka det.",
        "cta_button": "Skicka för offert",
        "service_section_eyebrow": "Omfattning",
        "faq_eyebrow": "FAQ",
        "faq_title": "Vanliga frågor inför offert",
        "quote_eyebrow": "Offert",
        "quote_cta_title": "Skicka foto, ritning eller beskrivning. Vi frågar om resten.",
        "quote_cta_button": "Gå till formulär",
        "realizations_eyebrow": "Referenser",
        "realizations_similar_cta": "Fråga om liknande projekt",
        "quote_submit": "Skicka förfrågan",
        "quote_quick_hint": "Beskriv ämnet kort och lämna telefonnummer eller e-post. Resten kan vi reda ut senare.",
        "quote_more_summary": "Mer information",
        "quote_more_hint": "Lägg gärna till företag, omfattning, plats, tidplan eller filer. Det hjälper oss att bedöma projektet snabbare, men är inte obligatoriskt.",
        "quote_aside_title": "Vad bör du bifoga?",
        "quote_aside_photo": "foto eller ritning av komponenten",
        "quote_aside_dimensions": "ungefärliga mått",
        "quote_aside_quantity": "antal: enstaka del, prov, serie eller återkommande samarbete",
        "quote_aside_material": "material och önskad ytbehandling",
        "quote_aside_timing": "tidplan och projektets land/stad",
        "quote_aside_note": "För B2B kan vi diskutera europeiskt samarbete. Logistik, packning och frakt bestäms efter att vi förstått komponenten.",
        "quote_guide_link": "Osäker på vad du ska förbereda? Se checklistan",
        "guide_slowdown_eyebrow": "Bra att veta",
        "contact_eyebrow": "Kajax Snickeri",
        "contact_data": "Kontaktuppgifter",
        "contact_address": "Adress",
        "contact_phone": "Telefon",
        "contact_email": "E-post",
        "contact_best_path": "Bästa vägen till offert",
        "contact_best_path_body": "Skicka formuläret med beskrivning, foto eller ritning. Då kan vi snabbare bedöma om uppdraget passar verkstaden och vad som saknas.",
        "contact_project_cta": "Skicka projekt",
    },
    "da": {
        "skip_link": "Gå til indhold",
        "nav_aria": "Hovednavigation",
        "mobile_actions_aria": "Hurtig kontakt",
        "mobile_call": "Ring",
        "mobile_quote": "Tilbud",
        "brand_tagline": "produktions- og byggesnedkeri",
        "footer_contact": "Kontakt",
        "footer_quote": "Tilbudsanmodning",
        "footer_about": "Et snedkeri fra Gościcino for virksomheder, arkitekter og investorer, der har brug for træarbejde udført solidt og teknisk gennemtænkt.",
        "footer_quote_body": "Start gerne med et foto, en tegning eller en specifikation. Vi spørger ind til materiale, antal, tidsplan og logistik.",
        "footer_quote_link": "Gå til tilbudsformularen",
        "footer_guide_link": "Sådan forbereder du en forespørgsel",
        "trust_aria": "Vigtigste styrker",
        "trust_region": "Pommern",
        "trust_series": "korte serier",
        "trust_specs": "tegninger og specifikationer",
        "trust_custom": "special- og byggesnedkeri",
        "home_paths_eyebrow": "Tilbud",
        "home_paths_title": "Træarbejde til produktion, interiører og specialprojekter",
        "home_b2b_eyebrow": "B2B-retning",
        "home_b2b_title": "Har du brug for gentagelige trækomponenter?",
        "home_b2b_body": "Vi kan fremstille en prototype, en kort serie eller gentagelige komponenter efter prøve. Det passer til virksomheder, der har brug for et pålideligt værksted uden at opbygge eget lille snedkeri.",
        "home_b2b_item_photo": "komponenter efter foto eller tegning",
        "home_b2b_item_series": "prøver og korte serier",
        "home_b2b_item_coop": "løbende samarbejde efter procesafstemning",
        "home_b2b_item_shipping": "pakning og forsendelse aftales individuelt",
        "home_b2b_cta": "Spørg om komponentproduktion",
        "home_b2b_image_alt": "Træprofiler og lister som eksempel på gentagelige komponenter",
        "process_eyebrow": "Tilbudsproces",
        "process_title": "Jo bedre input, desto hurtigere kan vi vurdere projektet",
        "process_guide_cta": "Se checklisten til tilbud",
        "portfolio_eyebrow": "Referencer",
        "portfolio_title": "Udvalgte arbejdsområder, der viser hvad værkstedet kan håndtere",
        "portfolio_cta": "Se referencer",
        "cta_eyebrow": "Har du et foto, en tegning eller specifikation?",
        "cta_title": "Send projektet. Vi vurderer, om vi kan fremstille det.",
        "cta_button": "Send til tilbud",
        "service_section_eyebrow": "Omfang",
        "faq_eyebrow": "FAQ",
        "faq_title": "Typiske spørgsmål før tilbud",
        "quote_eyebrow": "Tilbud",
        "quote_cta_title": "Send foto, tegning eller beskrivelse. Vi spørger om resten.",
        "quote_cta_button": "Gå til formular",
        "realizations_eyebrow": "Referencer",
        "realizations_similar_cta": "Spørg om et lignende projekt",
        "quote_submit": "Send forespørgsel",
        "quote_quick_hint": "Beskriv kort emnet og angiv telefon eller e-mail. Resten kan vi afklare senere.",
        "quote_more_summary": "Flere oplysninger",
        "quote_more_hint": "Tilføj eventuelt virksomhed, omfang, placering, tidsplan eller filer. Det hjælper os med at vurdere projektet hurtigere, men er ikke påkrævet.",
        "quote_aside_title": "Hvad bør du vedhæfte?",
        "quote_aside_photo": "foto eller tegning af komponenten",
        "quote_aside_dimensions": "omtrentlige mål",
        "quote_aside_quantity": "antal: én del, prøve, serie eller løbende samarbejde",
        "quote_aside_material": "materiale og ønsket finish",
        "quote_aside_timing": "tidsplan og projektets land/by",
        "quote_aside_note": "For B2B kan vi tale om europæisk samarbejde. Logistik, pakning og forsendelse aftales efter, at vi kender komponenten.",
        "quote_guide_link": "Ikke sikker på hvad du skal forberede? Se checklisten",
        "guide_slowdown_eyebrow": "Værd at vide",
        "contact_eyebrow": "Kajax Snedkeri",
        "contact_data": "Kontaktoplysninger",
        "contact_address": "Adresse",
        "contact_phone": "Telefon",
        "contact_email": "E-mail",
        "contact_best_path": "Bedste vej til tilbud",
        "contact_best_path_body": "Send formularen med beskrivelse, foto eller tegning. Det gør det hurtigere at vurdere, om opgaven passer til værkstedet, og hvilke oplysninger der mangler.",
        "contact_project_cta": "Send projekt",
    },
    "no": {
        "skip_link": "Gå til innhold",
        "nav_aria": "Hovednavigasjon",
        "mobile_actions_aria": "Rask kontakt",
        "mobile_call": "Ring",
        "mobile_quote": "Forespørsel",
        "brand_tagline": "produksjons- og byggsnekkerverksted",
        "footer_contact": "Kontakt",
        "footer_quote": "Forespørsel",
        "footer_about": "Et snekkerverksted fra Gościcino for bedrifter, arkitekter og investorer som trenger trearbeid utført grundig og teknisk gjennomtenkt.",
        "footer_quote_body": "Start gjerne med et bilde, en tegning eller en spesifikasjon. Vi spør om materiale, antall, tidsplan og logistikk.",
        "footer_quote_link": "Gå til forespørselsskjemaet",
        "footer_guide_link": "Slik forbereder du en forespørsel",
        "trust_aria": "Viktigste styrker",
        "trust_region": "Pommern",
        "trust_series": "korte serier",
        "trust_specs": "tegninger og spesifikasjoner",
        "trust_custom": "spesial- og byggsnekkerarbeid",
        "home_paths_eyebrow": "Tilbud",
        "home_paths_title": "Trearbeid for produksjon, interiør og spesialprosjekter",
        "home_b2b_eyebrow": "B2B-retning",
        "home_b2b_title": "Trenger du repeterbare trekomponenter?",
        "home_b2b_body": "Vi kan lage en prototype, en kort serie eller repeterbare komponenter basert på prøve. Det passer for bedrifter som trenger et pålitelig verksted uten å bygge sitt eget lille snekkerverksted.",
        "home_b2b_item_photo": "komponenter etter bilde eller tegning",
        "home_b2b_item_series": "prøver og korte serier",
        "home_b2b_item_coop": "fast samarbeid etter at prosessen er avklart",
        "home_b2b_item_shipping": "pakking og frakt avtales individuelt",
        "home_b2b_cta": "Spør om komponentproduksjon",
        "home_b2b_image_alt": "Treprofiler og lister som eksempel på repeterbare komponenter",
        "process_eyebrow": "Forespørselsprosess",
        "process_title": "Jo bedre grunnlag, desto raskere kan vi vurdere prosjektet",
        "process_guide_cta": "Se sjekklisten for forespørsel",
        "portfolio_eyebrow": "Referanser",
        "portfolio_title": "Utvalgte arbeidsområder som viser hva verkstedet kan håndtere",
        "portfolio_cta": "Se referanser",
        "cta_eyebrow": "Har du et bilde, en tegning eller spesifikasjon?",
        "cta_title": "Send prosjektet. Vi vurderer om vi kan lage det.",
        "cta_button": "Send til vurdering",
        "service_section_eyebrow": "Omfang",
        "faq_eyebrow": "FAQ",
        "faq_title": "Vanlige spørsmål før forespørsel",
        "quote_eyebrow": "Forespørsel",
        "quote_cta_title": "Send bilde, tegning eller beskrivelse. Vi spør om resten.",
        "quote_cta_button": "Gå til skjema",
        "realizations_eyebrow": "Referanser",
        "realizations_similar_cta": "Spør om et lignende prosjekt",
        "quote_submit": "Send forespørsel",
        "quote_quick_hint": "Beskriv temaet kort og legg igjen telefon eller e-post. Resten kan vi avklare senere.",
        "quote_more_summary": "Mer informasjon",
        "quote_more_hint": "Legg gjerne til firma, omfang, sted, tidsplan eller filer. Det hjelper oss å vurdere prosjektet raskere, men er ikke påkrevd.",
        "quote_aside_title": "Hva bør du legge ved?",
        "quote_aside_photo": "bilde eller tegning av komponenten",
        "quote_aside_dimensions": "omtrentlige mål",
        "quote_aside_quantity": "antall: én del, prøve, serie eller fast samarbeid",
        "quote_aside_material": "materiale og ønsket finish",
        "quote_aside_timing": "tidsplan og prosjektets land/by",
        "quote_aside_note": "For B2B kan vi diskutere europeisk samarbeid. Logistikk, pakking og frakt avtales etter at vi forstår komponenten.",
        "quote_guide_link": "Usikker på hva du skal forberede? Se sjekklisten",
        "guide_slowdown_eyebrow": "Verdt å vite",
        "contact_eyebrow": "Kajax Snekkerverksted",
        "contact_data": "Kontaktinformasjon",
        "contact_address": "Adresse",
        "contact_phone": "Telefon",
        "contact_email": "E-post",
        "contact_best_path": "Beste vei til vurdering",
        "contact_best_path_body": "Send skjemaet med beskrivelse, bilde eller tegning. Da kan vi raskere vurdere om oppdraget passer verkstedet og hvilken informasjon som mangler.",
        "contact_project_cta": "Send prosjekt",
    },
}


def get_ui_copy(language_code):
    normalized = (language_code or "pl").split("-")[0]
    return UI_COPY.get(normalized, UI_COPY["pl"])
