UI_COPY = {
    "pl": {
        "skip_link": "Przejdź do treści",
        "nav_aria": "Główna nawigacja",
        "language_aria": "Wybór języka",
        "mobile_actions_aria": "Szybki kontakt",
        "mobile_call": "Zadzwoń",
        "mobile_quote": "Wycena",
        "brand_tagline": "stolarnia z Gościcina",
        "footer_contact": "Kontakt",
        "footer_quote": "Zapytanie",
        "footer_about": "Stolarnia z Gościcina. Robimy komponenty drewniane dla firm oraz schody, drzwi, listwy i zabudowy w Pomorskiem.",
        "footer_quote_body": "Wyślij zdjęcie, rysunek, wzór albo krótki opis. Odpowiemy, czy temat pasuje do warsztatu i czego brakuje do wyceny.",
        "footer_quote_link": "Wyślij zapytanie",
        "footer_guide_link": "Jak opisać zlecenie",
        "trust_aria": "Najważniejsze wyróżniki",
        "trust_region": "B2B: elementy z drewna",
        "trust_series": "Pomorskie: schody i drzwi",
        "trust_specs": "próbka przed serią",
        "trust_custom": "rysunek, wzór albo zdjęcie",
        "home_paths_eyebrow": "Oferta",
        "home_paths_title": "Dwa główne kierunki: produkcja dla firm i stolarka lokalna",
        "home_b2b_eyebrow": "Dla firm",
        "home_b2b_title": "Komponent drewniany bez uruchamiania własnej stolarni",
        "home_b2b_body": "Jeśli firma potrzebuje drewnianej części do produktu, ekspozycji, lokalu albo dalszego montażu, możemy przejąć konkretny fragment pracy: próbkę, partię testową lub krótką serię.",
        "home_b2b_item_photo": "start od zdjęcia, wzoru, rysunku lub specyfikacji",
        "home_b2b_item_series": "najpierw próbka lub partia testowa, potem powtarzalne zamówienia",
        "home_b2b_item_coop": "profile, listwy, elementy POS i półprodukty dla firm",
        "home_b2b_item_shipping": "pakowanie, odbiór lub wysyłka po ocenie gabarytu",
        "home_b2b_cta": "Zobacz produkcję dla firm",
        "home_b2b_image_alt": "Seria drewnianych elementów ułożona na stole warsztatowym",
        "process_eyebrow": "Jak zacząć",
        "process_title": "Od zdjęcia lub rysunku do konkretnej odpowiedzi",
        "process_guide_cta": "Sprawdź checklistę",
        "portfolio_eyebrow": "Przykłady",
        "portfolio_title": "Przykłady zapytań, które pasują do warsztatu",
        "portfolio_cta": "Zobacz realizacje",
        "cta_eyebrow": "Masz coś do wykonania z drewna?",
        "cta_title": "Wyślij zdjęcie, rysunek albo wzór. Odpowiemy, czy temat pasuje do warsztatu.",
        "cta_button": "Wyślij zapytanie",
        "service_section_eyebrow": "Temat",
        "faq_eyebrow": "FAQ",
        "faq_title": "Najczęstsze pytania przed pierwszą rozmową",
        "quote_eyebrow": "Wycena",
        "quote_cta_title": "Masz zdjęcie, rysunek albo wzór? Wyślij go do pierwszej oceny.",
        "quote_cta_button": "Wyślij zapytanie",
        "realizations_eyebrow": "Realizacje",
        "realizations_similar_cta": "Zapytaj o podobny temat",
        "quote_submit": "Wyślij zapytanie",
        "quote_quick_hint": "Wystarczy kilka zdań. Napisz, co ma powstać, w jakiej ilości lub gdzie ma być montowane. Zostaw telefon albo email, a wrócimy z konkretnymi pytaniami.",
        "quote_more_summary": "Mam więcej danych",
        "quote_more_hint": "Tu możesz dodać firmę, liczbę sztuk, lokalizację, termin albo pliki, jeśli masz je pod ręką.",
        "quote_aside_title": "Co przyspiesza odpowiedź?",
        "quote_aside_photo": "zdjęcie, rysunek, wzór lub podobny przykład",
        "quote_aside_dimensions": "wymiary albo orientacyjny rozmiar",
        "quote_aside_quantity": "liczba sztuk, próbka lub planowana seria",
        "quote_aside_material": "materiał, kolor albo oczekiwane wykończenie",
        "quote_aside_timing": "termin, miejscowość i sposób odbioru",
        "quote_aside_note": "Dla firm możemy rozmawiać o odbiorze i wysyłce poza Pomorskie. Pakowanie i transport oceniamy po poznaniu wymiarów, materiału i liczby sztuk.",
        "quote_guide_link": "Jak opisać zlecenie",
        "guide_slowdown_eyebrow": "Warto wiedzieć",
        "contact_eyebrow": "Kajax Stolarstwo",
        "contact_data": "Dane kontaktowe",
        "contact_address": "Adres",
        "contact_phone": "Telefon",
        "contact_email": "Email",
        "contact_best_path": "Najlepszy start to zdjęcie, rysunek albo wzór",
        "contact_best_path_body": "Zamiast opisywać wszystko od zera, pokaż element lub miejsce. Szybciej ocenimy, czy temat pasuje do warsztatu i czego brakuje do wyceny.",
        "contact_project_cta": "Wyślij zapytanie",
    },
    "en": {
        "skip_link": "Skip to content",
        "nav_aria": "Main navigation",
        "language_aria": "Language selection",
        "mobile_actions_aria": "Quick contact",
        "mobile_call": "Call",
        "mobile_quote": "Quote",
        "brand_tagline": "joinery workshop in Gościcino",
        "footer_contact": "Contact",
        "footer_quote": "Quote request",
        "footer_about": "A Gościcino joinery workshop for companies that need wooden components, short runs and project-based details made from a drawing, sample or specification.",
        "footer_quote_body": "The best starting point is a photo, drawing or specification. We will ask about material, quantity, timing, finish and logistics.",
        "footer_quote_link": "Go to the quote form",
        "footer_guide_link": "How to prepare an inquiry",
        "trust_aria": "Key strengths",
        "trust_region": "Pomerania",
        "trust_series": "short series",
        "trust_specs": "drawings and specifications",
        "trust_custom": "stairs, doors and details",
        "home_paths_eyebrow": "Offer",
        "home_paths_title": "What you can send us",
        "home_b2b_eyebrow": "For companies",
        "home_b2b_title": "Do you need repeatable wooden components?",
        "home_b2b_body": "We can prepare a prototype, a short run or repeatable components based on a sample. This fits companies that need wooden semi-finished parts, POS details or components for further assembly without building their own joinery operation.",
        "home_b2b_item_photo": "components based on a photo or drawing",
        "home_b2b_item_series": "trial runs and short batches",
        "home_b2b_item_coop": "recurring cooperation after the process is aligned",
        "home_b2b_item_shipping": "packing and shipping agreed individually",
        "home_b2b_cta": "Ask about component production",
        "home_b2b_image_alt": "Wooden profiles and trims as an example of repeatable components",
        "process_eyebrow": "How we start",
        "process_title": "From a photo or drawing to a concrete conversation",
        "process_guide_cta": "See the quote checklist",
        "portfolio_eyebrow": "Realizations",
        "portfolio_title": "B2B examples worth assessing",
        "portfolio_cta": "View realizations",
        "cta_eyebrow": "Do you have a photo, drawing or specification?",
        "cta_title": "Send the topic and we will tell you what comes next.",
        "cta_button": "Send for quote",
        "service_section_eyebrow": "Scope",
        "faq_eyebrow": "FAQ",
        "faq_title": "Common questions before a quote",
        "quote_eyebrow": "Quote",
        "quote_cta_title": "Send a photo, drawing or description. We will quickly clarify what is missing for pricing.",
        "quote_cta_button": "Go to form",
        "realizations_eyebrow": "Realizations",
        "realizations_similar_cta": "Ask about a similar project",
        "quote_submit": "Send inquiry",
        "quote_quick_hint": "Briefly describe the component, batch or joinery project and leave a phone number or email. A few concrete sentences are enough to start.",
        "quote_more_summary": "More information",
        "quote_more_hint": "Optionally add company, scale, location, timing or files. It speeds up assessment, but it does not block sending the inquiry.",
        "quote_aside_title": "What should you include?",
        "quote_aside_photo": "photo or drawing of the component",
        "quote_aside_dimensions": "approximate dimensions",
        "quote_aside_quantity": "quantity: one piece, sample, batch or recurring cooperation",
        "quote_aside_material": "material and expected finish",
        "quote_aside_timing": "timing and country/city of the project",
        "quote_aside_note": "For B2B projects we can discuss cooperation in Poland and Europe. Logistics, packing and shipping are agreed only after we understand the component.",
        "quote_guide_link": "Not sure what to prepare? See the checklist",
        "guide_slowdown_eyebrow": "Worth knowing",
        "contact_eyebrow": "Kajax Joinery",
        "contact_data": "Contact details",
        "contact_address": "Address",
        "contact_phone": "Phone",
        "contact_email": "Email",
        "contact_best_path": "Best path to a quote",
        "contact_best_path_body": "Send the form with a description, photo or drawing. It helps us assess whether the topic fits the workshop, what the risks are and what information is still missing.",
        "contact_project_cta": "Send project",
    },
    "de": {
        "skip_link": "Zum Inhalt springen",
        "nav_aria": "Hauptnavigation",
        "language_aria": "Sprachauswahl",
        "mobile_actions_aria": "Schneller Kontakt",
        "mobile_call": "Anrufen",
        "mobile_quote": "Anfrage",
        "brand_tagline": "Tischlerei in Gościcino",
        "footer_contact": "Kontakt",
        "footer_quote": "Anfrage",
        "footer_about": "Eine Tischlerei aus Gościcino für Unternehmen, Architekten und Investoren, die Holzelemente sauber, technisch sinnvoll und ohne vage Versprechen benötigen.",
        "footer_quote_body": "Am besten senden Sie ein Foto, eine Zeichnung oder eine Spezifikation. Wir fragen nach Material, Menge, Termin, Oberfläche und Logistik.",
        "footer_quote_link": "Zum Anfrageformular",
        "footer_guide_link": "Anfrage vorbereiten",
        "trust_aria": "Wichtigste Stärken",
        "trust_region": "Pommern",
        "trust_series": "Kleinserien",
        "trust_specs": "Zeichnungen und Spezifikationen",
        "trust_custom": "Sonderanfertigungen und Bauschreinerei",
        "home_paths_eyebrow": "Angebot",
        "home_paths_title": "Womit Sie sich an uns wenden können",
        "home_b2b_eyebrow": "Für Unternehmen",
        "home_b2b_title": "Benötigen Sie wiederholbare Holzelemente?",
        "home_b2b_body": "Wir können einen Prototyp, eine Kleinserie oder wiederholbare Elemente nach Muster vorbereiten. Das passt zu Firmen, die Holz-Halbzeuge, POS-Details oder Teile zur weiteren Montage brauchen, ohne eigene Tischlereikapazität aufzubauen.",
        "home_b2b_item_photo": "Elemente nach Foto oder Zeichnung",
        "home_b2b_item_series": "Probeläufe und Kleinserien",
        "home_b2b_item_coop": "regelmäßige Zusammenarbeit nach Prozessabstimmung",
        "home_b2b_item_shipping": "Verpackung und Versand individuell zu klären",
        "home_b2b_cta": "Elementproduktion anfragen",
        "home_b2b_image_alt": "Holzprofile und Leisten als Beispiel wiederholbarer Elemente",
        "process_eyebrow": "So starten wir",
        "process_title": "Vom Foto oder der Zeichnung zum konkreten Gespräch",
        "process_guide_cta": "Checkliste zur Anfrage ansehen",
        "portfolio_eyebrow": "Referenzen",
        "portfolio_title": "Beispiele für Themen, die sich zur Prüfung lohnen",
        "portfolio_cta": "Referenzen ansehen",
        "cta_eyebrow": "Haben Sie ein Foto, eine Zeichnung oder Spezifikation?",
        "cta_title": "Senden Sie das Thema. Wir sagen, was der nächste Schritt ist.",
        "cta_button": "Zur Anfrage senden",
        "service_section_eyebrow": "Umfang",
        "faq_eyebrow": "FAQ",
        "faq_title": "Häufige Fragen vor der Anfrage",
        "quote_eyebrow": "Anfrage",
        "quote_cta_title": "Senden Sie Foto, Zeichnung oder Beschreibung. Wir klären schnell, was für die Anfrage noch fehlt.",
        "quote_cta_button": "Zum Formular",
        "realizations_eyebrow": "Referenzen",
        "realizations_similar_cta": "Ähnliches Projekt anfragen",
        "quote_submit": "Anfrage senden",
        "quote_quick_hint": "Beschreiben Sie kurz Element, Serie oder Schreinerarbeit und hinterlassen Sie Telefon oder E-Mail. Einige konkrete Sätze reichen für den Start.",
        "quote_more_summary": "Weitere Informationen",
        "quote_more_hint": "Optional können Sie Firma, Umfang, Standort, Zeitrahmen oder Dateien ergänzen. Das beschleunigt die Einschätzung, blockiert die Anfrage aber nicht.",
        "quote_aside_title": "Was sollte enthalten sein?",
        "quote_aside_photo": "Foto oder Zeichnung des Elements",
        "quote_aside_dimensions": "ungefähre Maße",
        "quote_aside_quantity": "Menge: Einzelstück, Muster, Serie oder regelmäßige Zusammenarbeit",
        "quote_aside_material": "Material und gewünschte Oberfläche",
        "quote_aside_timing": "Termin sowie Land/Stadt des Projekts",
        "quote_aside_note": "Für B2B-Projekte können wir über Zusammenarbeit in Polen und Europa sprechen. Logistik, Verpackung und Versand werden erst nach Prüfung des Elements festgelegt.",
        "quote_guide_link": "Nicht sicher, was Sie vorbereiten sollen? Zur Checkliste",
        "guide_slowdown_eyebrow": "Gut zu wissen",
        "contact_eyebrow": "Kajax Tischlerei",
        "contact_data": "Kontaktdaten",
        "contact_address": "Adresse",
        "contact_phone": "Telefon",
        "contact_email": "E-Mail",
        "contact_best_path": "Der beste Weg zur Anfrage",
        "contact_best_path_body": "Senden Sie das Formular mit Beschreibung, Foto oder Zeichnung. So können wir schneller prüfen, ob das Thema zur Werkstatt passt, welche Risiken bestehen und welche Informationen fehlen.",
        "contact_project_cta": "Projekt senden",
    },
    "sv": {
        "skip_link": "Hoppa till innehåll",
        "nav_aria": "Huvudnavigering",
        "language_aria": "Språkval",
        "mobile_actions_aria": "Snabb kontakt",
        "mobile_call": "Ring",
        "mobile_quote": "Offert",
        "brand_tagline": "snickeri i Gościcino",
        "footer_contact": "Kontakt",
        "footer_quote": "Offertförfrågan",
        "footer_about": "Ett snickeri från Gościcino för företag, arkitekter och investerare som behöver träkomponenter utförda noggrant, tekniskt genomtänkt och utan vaga löften.",
        "footer_quote_body": "Börja gärna med ett foto, en ritning eller en specifikation. Vi frågar om material, antal, tidplan, finish och logistik.",
        "footer_quote_link": "Gå till offertformuläret",
        "footer_guide_link": "Så förbereder du en förfrågan",
        "trust_aria": "Viktigaste styrkor",
        "trust_region": "Pommern",
        "trust_series": "korta serier",
        "trust_specs": "ritningar och specifikationer",
        "trust_custom": "special- och byggsnickeri",
        "home_paths_eyebrow": "Erbjudande",
        "home_paths_title": "Vad du kan skicka till oss",
        "home_b2b_eyebrow": "För företag",
        "home_b2b_title": "Behöver du återkommande träkomponenter?",
        "home_b2b_body": "Vi kan ta fram en prototyp, en kort serie eller återkommande komponenter efter prov. Det passar företag som behöver halvfabrikat i trä, POS-detaljer eller komponenter för vidare montage utan att bygga eget snickeri.",
        "home_b2b_item_photo": "komponenter efter foto eller ritning",
        "home_b2b_item_series": "prover och korta serier",
        "home_b2b_item_coop": "återkommande samarbete efter processanpassning",
        "home_b2b_item_shipping": "packning och frakt avtalas individuellt",
        "home_b2b_cta": "Fråga om komponentproduktion",
        "home_b2b_image_alt": "Träprofiler och lister som exempel på återkommande komponenter",
        "process_eyebrow": "Så börjar vi",
        "process_title": "Från foto eller ritning till konkret dialog",
        "process_guide_cta": "Se checklistan för offert",
        "portfolio_eyebrow": "Referenser",
        "portfolio_title": "Exempel på uppdrag som är värda att skicka för bedömning",
        "portfolio_cta": "Visa referenser",
        "cta_eyebrow": "Har du ett foto, en ritning eller specifikation?",
        "cta_title": "Skicka ämnet. Vi säger vad nästa steg är.",
        "cta_button": "Skicka för offert",
        "service_section_eyebrow": "Omfattning",
        "faq_eyebrow": "FAQ",
        "faq_title": "Vanliga frågor inför offert",
        "quote_eyebrow": "Offert",
        "quote_cta_title": "Skicka foto, ritning eller beskrivning. Vi klargör snabbt vad som saknas för offert.",
        "quote_cta_button": "Gå till formulär",
        "realizations_eyebrow": "Referenser",
        "realizations_similar_cta": "Fråga om liknande projekt",
        "quote_submit": "Skicka förfrågan",
        "quote_quick_hint": "Beskriv kort komponenten, serien eller snickeriet och lämna telefon eller e-post. Några konkreta meningar räcker för start.",
        "quote_more_summary": "Mer information",
        "quote_more_hint": "Lägg gärna till företag, omfattning, plats, tidplan eller filer. Det snabbar upp bedömningen men stoppar inte förfrågan.",
        "quote_aside_title": "Vad bör du bifoga?",
        "quote_aside_photo": "foto eller ritning av komponenten",
        "quote_aside_dimensions": "ungefärliga mått",
        "quote_aside_quantity": "antal: enstaka del, prov, serie eller återkommande samarbete",
        "quote_aside_material": "material och önskad ytbehandling",
        "quote_aside_timing": "tidplan och projektets land/stad",
        "quote_aside_note": "För B2B kan vi diskutera samarbete i Polen och Europa. Logistik, packning och frakt bestäms först när vi förstått komponenten.",
        "quote_guide_link": "Osäker på vad du ska förbereda? Se checklistan",
        "guide_slowdown_eyebrow": "Bra att veta",
        "contact_eyebrow": "Kajax Snickeri",
        "contact_data": "Kontaktuppgifter",
        "contact_address": "Adress",
        "contact_phone": "Telefon",
        "contact_email": "E-post",
        "contact_best_path": "Bästa vägen till offert",
        "contact_best_path_body": "Skicka formuläret med beskrivning, foto eller ritning. Då kan vi snabbare bedöma om uppdraget passar verkstaden, vilka risker som finns och vad som saknas.",
        "contact_project_cta": "Skicka projekt",
    },
    "da": {
        "skip_link": "Gå til indhold",
        "nav_aria": "Hovednavigation",
        "language_aria": "Sprogvalg",
        "mobile_actions_aria": "Hurtig kontakt",
        "mobile_call": "Ring",
        "mobile_quote": "Tilbud",
        "brand_tagline": "snedkeri i Gościcino",
        "footer_contact": "Kontakt",
        "footer_quote": "Tilbudsanmodning",
        "footer_about": "Et snedkeri fra Gościcino for virksomheder, der har brug for trækomponenter, korte serier og projektdetaljer efter tegning, prøve eller specifikation.",
        "footer_quote_body": "Start gerne med et foto, en tegning eller en specifikation. Vi spørger ind til materiale, antal, tidsplan, finish og logistik.",
        "footer_quote_link": "Gå til tilbudsformularen",
        "footer_guide_link": "Sådan forbereder du en forespørgsel",
        "trust_aria": "Vigtigste styrker",
        "trust_region": "Pommern",
        "trust_series": "korte serier",
        "trust_specs": "tegninger og specifikationer",
        "trust_custom": "special- og byggesnedkeri",
        "home_paths_eyebrow": "Tilbud",
        "home_paths_title": "Hvad du kan sende til os",
        "home_b2b_eyebrow": "For virksomheder",
        "home_b2b_title": "Har du brug for gentagelige trækomponenter?",
        "home_b2b_body": "Vi kan fremstille en prototype, en kort serie eller gentagelige komponenter efter prøve. Det passer til virksomheder, der har brug for halvfabrikata i træ, POS-detaljer eller komponenter til videre montage uden at opbygge eget snedkeri.",
        "home_b2b_item_photo": "komponenter efter foto eller tegning",
        "home_b2b_item_series": "prøver og korte serier",
        "home_b2b_item_coop": "løbende samarbejde efter procesafstemning",
        "home_b2b_item_shipping": "pakning og forsendelse aftales individuelt",
        "home_b2b_cta": "Spørg om komponentproduktion",
        "home_b2b_image_alt": "Træprofiler og lister som eksempel på gentagelige komponenter",
        "process_eyebrow": "Sådan starter vi",
        "process_title": "Fra foto eller tegning til konkret dialog",
        "process_guide_cta": "Se checklisten til tilbud",
        "portfolio_eyebrow": "Referencer",
        "portfolio_title": "Eksempler på opgaver der er værd at sende til vurdering",
        "portfolio_cta": "Se referencer",
        "cta_eyebrow": "Har du et foto, en tegning eller specifikation?",
        "cta_title": "Send emnet. Vi siger, hvad næste skridt er.",
        "cta_button": "Send til tilbud",
        "service_section_eyebrow": "Omfang",
        "faq_eyebrow": "FAQ",
        "faq_title": "Typiske spørgsmål før tilbud",
        "quote_eyebrow": "Tilbud",
        "quote_cta_title": "Send foto, tegning eller beskrivelse. Vi afklarer hurtigt, hvad der mangler til tilbud.",
        "quote_cta_button": "Gå til formular",
        "realizations_eyebrow": "Referencer",
        "realizations_similar_cta": "Spørg om et lignende projekt",
        "quote_submit": "Send forespørgsel",
        "quote_quick_hint": "Beskriv kort komponenten, serien eller snedkerarbejdet og angiv telefon eller e-mail. Få konkrete sætninger er nok til start.",
        "quote_more_summary": "Flere oplysninger",
        "quote_more_hint": "Tilføj eventuelt virksomhed, omfang, placering, tidsplan eller filer. Det gør vurderingen hurtigere, men stopper ikke forespørgslen.",
        "quote_aside_title": "Hvad bør du vedhæfte?",
        "quote_aside_photo": "foto eller tegning af komponenten",
        "quote_aside_dimensions": "omtrentlige mål",
        "quote_aside_quantity": "antal: én del, prøve, serie eller løbende samarbejde",
        "quote_aside_material": "materiale og ønsket finish",
        "quote_aside_timing": "tidsplan og projektets land/by",
        "quote_aside_note": "For B2B kan vi tale om samarbejde i Polen og Europa. Logistik, pakning og forsendelse aftales først, når vi kender komponenten.",
        "quote_guide_link": "Ikke sikker på hvad du skal forberede? Se checklisten",
        "guide_slowdown_eyebrow": "Værd at vide",
        "contact_eyebrow": "Kajax Snedkeri",
        "contact_data": "Kontaktoplysninger",
        "contact_address": "Adresse",
        "contact_phone": "Telefon",
        "contact_email": "E-mail",
        "contact_best_path": "Bedste vej til tilbud",
        "contact_best_path_body": "Send formularen med beskrivelse, foto eller tegning. Det gør det hurtigere at vurdere, om opgaven passer til værkstedet, hvilke risici der er, og hvilke oplysninger der mangler.",
        "contact_project_cta": "Send projekt",
    },
    "no": {
        "skip_link": "Gå til innhold",
        "nav_aria": "Hovednavigasjon",
        "language_aria": "Språkvalg",
        "mobile_actions_aria": "Rask kontakt",
        "mobile_call": "Ring",
        "mobile_quote": "Forespørsel",
        "brand_tagline": "snekkerverksted i Gościcino",
        "footer_contact": "Kontakt",
        "footer_quote": "Forespørsel",
        "footer_about": "Et snekkerverksted fra Gościcino for bedrifter som trenger trekomponenter, korte serier og prosjektdetaljer etter tegning, prøve eller spesifikasjon.",
        "footer_quote_body": "Start gjerne med et bilde, en tegning eller en spesifikasjon. Vi spør om materiale, antall, tidsplan, overflate og logistikk.",
        "footer_quote_link": "Gå til forespørselsskjemaet",
        "footer_guide_link": "Slik forbereder du en forespørsel",
        "trust_aria": "Viktigste styrker",
        "trust_region": "Pommern",
        "trust_series": "korte serier",
        "trust_specs": "tegninger og spesifikasjoner",
        "trust_custom": "spesial- og byggsnekkerarbeid",
        "home_paths_eyebrow": "Tilbud",
        "home_paths_title": "Hva du kan sende til oss",
        "home_b2b_eyebrow": "For bedrifter",
        "home_b2b_title": "Trenger du repeterbare trekomponenter?",
        "home_b2b_body": "Vi kan lage en prototype, en kort serie eller repeterbare komponenter basert på prøve. Det passer for bedrifter som trenger halvfabrikata i tre, POS-detaljer eller komponenter for videre montering uten å bygge eget snekkerverksted.",
        "home_b2b_item_photo": "komponenter etter bilde eller tegning",
        "home_b2b_item_series": "prøver og korte serier",
        "home_b2b_item_coop": "fast samarbeid etter at prosessen er avklart",
        "home_b2b_item_shipping": "pakking og frakt avtales individuelt",
        "home_b2b_cta": "Spør om komponentproduksjon",
        "home_b2b_image_alt": "Treprofiler og lister som eksempel på repeterbare komponenter",
        "process_eyebrow": "Slik starter vi",
        "process_title": "Fra bilde eller tegning til konkret dialog",
        "process_guide_cta": "Se sjekklisten for forespørsel",
        "portfolio_eyebrow": "Referanser",
        "portfolio_title": "Eksempler på oppdrag som er verdt å sende til vurdering",
        "portfolio_cta": "Se referanser",
        "cta_eyebrow": "Har du et bilde, en tegning eller spesifikasjon?",
        "cta_title": "Send temaet. Vi sier hva neste steg er.",
        "cta_button": "Send til vurdering",
        "service_section_eyebrow": "Omfang",
        "faq_eyebrow": "FAQ",
        "faq_title": "Vanlige spørsmål før forespørsel",
        "quote_eyebrow": "Forespørsel",
        "quote_cta_title": "Send bilde, tegning eller beskrivelse. Vi avklarer raskt hva som mangler for pris.",
        "quote_cta_button": "Gå til skjema",
        "realizations_eyebrow": "Referanser",
        "realizations_similar_cta": "Spør om et lignende prosjekt",
        "quote_submit": "Send forespørsel",
        "quote_quick_hint": "Beskriv kort komponenten, serien eller snekkerarbeidet og legg igjen telefon eller e-post. Noen konkrete setninger er nok for start.",
        "quote_more_summary": "Mer informasjon",
        "quote_more_hint": "Legg gjerne til firma, omfang, sted, tidsplan eller filer. Det gjør vurderingen raskere, men stopper ikke forespørselen.",
        "quote_aside_title": "Hva bør du legge ved?",
        "quote_aside_photo": "bilde eller tegning av komponenten",
        "quote_aside_dimensions": "omtrentlige mål",
        "quote_aside_quantity": "antall: én del, prøve, serie eller fast samarbeid",
        "quote_aside_material": "materiale og ønsket finish",
        "quote_aside_timing": "tidsplan og prosjektets land/by",
        "quote_aside_note": "For B2B kan vi diskutere samarbeid i Polen og Europa. Logistikk, pakking og frakt avtales først når vi forstår komponenten.",
        "quote_guide_link": "Usikker på hva du skal forberede? Se sjekklisten",
        "guide_slowdown_eyebrow": "Verdt å vite",
        "contact_eyebrow": "Kajax Snekkerverksted",
        "contact_data": "Kontaktinformasjon",
        "contact_address": "Adresse",
        "contact_phone": "Telefon",
        "contact_email": "E-post",
        "contact_best_path": "Beste vei til vurdering",
        "contact_best_path_body": "Send skjemaet med beskrivelse, bilde eller tegning. Da kan vi raskere vurdere om oppdraget passer verkstedet, hvilke risikoer som finnes og hvilken informasjon som mangler.",
        "contact_project_cta": "Send prosjekt",
    },
}


_MENU_LABELS = {
    "pl": "Menu",
    "en": "Menu",
    "de": "Menü",
    "sv": "Meny",
    "da": "Menu",
    "no": "Meny",
}

_QUOTE_FILE_PROMPTS = {
    "pl": {
        "quote_file_prompt_strong": "Masz zdjęcie, rysunek albo wzór?",
        "quote_file_prompt": "Dodaj plik w sekcji „Mam więcej danych” albo opisz, co możesz dosłać później.",
    },
    "en": {
        "quote_file_prompt_strong": "Do you have a photo, drawing or sample?",
        "quote_file_prompt": "Add a file under “More information” or describe what you can send later.",
    },
    "de": {
        "quote_file_prompt_strong": "Haben Sie ein Foto, eine Zeichnung oder ein Muster?",
        "quote_file_prompt": "Fügen Sie die Datei unter „Weitere Informationen” hinzu oder beschreiben Sie, was Sie später senden können.",
    },
    "sv": {
        "quote_file_prompt_strong": "Har du ett foto, en ritning eller ett prov?",
        "quote_file_prompt": "Lägg till filen under ”Mer information” eller beskriv vad du kan skicka senare.",
    },
    "da": {
        "quote_file_prompt_strong": "Har du foto, tegning eller prøve?",
        "quote_file_prompt": "Tilføj filen under “Mere information” eller beskriv, hvad du kan sende senere.",
    },
    "no": {
        "quote_file_prompt_strong": "Har du bilde, tegning eller prøve?",
        "quote_file_prompt": "Legg til filen under «Mer informasjon» eller beskriv hva du kan sende senere.",
    },
}

FOREIGN_UI_B2B_REFOCUS = {
    "en": {
        "footer_about": "A Gościcino joinery workshop for companies that need wooden components, short runs, POS/display elements and project-based details made from a drawing, sample or specification.",
        "footer_quote_body": "Send a photo, drawing, sample or specification. We will ask about material, quantity, finish, deadline, packing and shipping.",
        "trust_region": "Poland and Europe",
        "trust_series": "sample before batch",
        "trust_specs": "drawings and specifications",
        "trust_custom": "POS, fit-out and B2B components",
        "home_paths_title": "Choose the B2B path",
        "home_b2b_title": "Do you need repeatable wooden components?",
        "home_b2b_body": "We can prepare a sample, short run or repeatable batch for companies that need wooden semi-finished parts, POS/display details or components for further assembly.",
        "home_b2b_item_photo": "components from a drawing, sample, photo or specification",
        "home_b2b_item_series": "sample or pilot batch before larger orders",
        "home_b2b_item_coop": "repeatable elements for manufacturers, agencies and contractors",
        "home_b2b_item_shipping": "packing, pickup or shipping agreed after assessment",
        "home_b2b_cta": "See B2B component production",
        "process_title": "From drawing or sample to the first batch",
        "portfolio_title": "B2B examples for assessment",
        "cta_title": "Send a drawing, sample or specification. We will tell you what the next step should be.",
        "quote_quick_hint": "Briefly describe the component, batch or fit-out element and leave a phone number or email. A few concrete details are enough to start.",
        "quote_more_hint": "Optionally add company, quantity, location, deadline or files. It speeds up assessment but does not block the inquiry.",
        "quote_aside_note": "For B2B components we can discuss work in Poland and Europe. Packing and shipping are assessed after we know dimensions, material and quantity.",
        "contact_best_path": "Best start: drawing, sample, photo or specification",
        "contact_best_path_body": "Show the component and its use instead of describing everything from scratch. We will assess fit, risks and missing data faster.",
    },
    "de": {
        "footer_about": "Tischlerei aus Gościcino für Unternehmen, die Holzelemente, Kleinserien, POS-/Display-Teile und Projektdetails nach Zeichnung, Muster oder Spezifikation brauchen.",
        "footer_quote_body": "Senden Sie Foto, Zeichnung, Muster oder Spezifikation. Wir fragen nach Material, Menge, Oberfläche, Termin, Verpackung und Versand.",
        "trust_region": "Polen und Europa",
        "trust_series": "Muster vor Serie",
        "trust_specs": "Zeichnungen und Spezifikationen",
        "trust_custom": "POS, Objektserien und B2B-Elemente",
        "home_paths_title": "Wählen Sie den B2B-Pfad",
        "home_b2b_title": "Benötigen Sie wiederholbare Holzelemente?",
        "home_b2b_body": "Wir können Muster, Kleinserie oder wiederholbare Charge für Unternehmen vorbereiten, die Holz-Halbzeuge, POS-/Display-Details oder Elemente zur weiteren Montage brauchen.",
        "home_b2b_item_photo": "Elemente nach Zeichnung, Muster, Foto oder Spezifikation",
        "home_b2b_item_series": "Muster oder Pilotcharge vor größeren Bestellungen",
        "home_b2b_item_coop": "wiederholbare Elemente für Hersteller, Agenturen und Ausbauer",
        "home_b2b_item_shipping": "Verpackung, Abholung oder Versand nach Prüfung",
        "home_b2b_cta": "B2B-Elementfertigung ansehen",
        "process_title": "Von Zeichnung oder Muster zur ersten Charge",
        "portfolio_title": "B2B-Beispiele für eine Anfrage",
        "cta_title": "Senden Sie Zeichnung, Muster oder Spezifikation. Wir sagen, welcher nächste Schritt sinnvoll ist.",
        "quote_quick_hint": "Beschreiben Sie kurz Element, Serie oder Objektteil und hinterlassen Sie Telefon oder E-Mail. Einige konkrete Angaben reichen für den Start.",
        "quote_more_hint": "Optional können Sie Firma, Menge, Standort, Termin oder Dateien ergänzen. Das beschleunigt die Einschätzung, blockiert die Anfrage aber nicht.",
        "quote_aside_note": "Für B2B-Elemente können wir über Zusammenarbeit in Polen und Europa sprechen. Verpackung und Versand prüfen wir nach Maßen, Material und Menge.",
        "contact_best_path": "Bester Start: Zeichnung, Muster, Foto oder Spezifikation",
        "contact_best_path_body": "Zeigen Sie das Element und seine Nutzung, statt alles von null zu beschreiben. So prüfen wir schneller Passung, Risiken und fehlende Daten.",
    },
    "sv": {
        "footer_about": "Snickeri från Gościcino för företag som behöver träkomponenter, korta serier, POS-/displaydelar och projektdetaljer efter ritning, prov eller specifikation.",
        "footer_quote_body": "Skicka foto, ritning, prov eller specifikation. Vi frågar om material, antal, finish, deadline, packning och frakt.",
        "trust_region": "Polen och Europa",
        "trust_series": "prov före serie",
        "trust_specs": "ritningar och specifikationer",
        "trust_custom": "POS, inredningsserier och B2B-komponenter",
        "home_paths_title": "Välj B2B-spår",
        "home_b2b_title": "Behöver du återkommande träkomponenter?",
        "home_b2b_body": "Vi kan ta fram prov, kort serie eller återkommande batch för företag som behöver halvfabrikat i trä, POS-/displaydetaljer eller komponenter för vidare montage.",
        "home_b2b_item_photo": "komponenter efter ritning, prov, foto eller specifikation",
        "home_b2b_item_series": "prov eller pilotbatch före större order",
        "home_b2b_item_coop": "återkommande element för producenter, byråer och entreprenörer",
        "home_b2b_item_shipping": "packning, upphämtning eller frakt efter bedömning",
        "home_b2b_cta": "Se B2B-komponentproduktion",
        "process_title": "Från ritning eller prov till första batch",
        "portfolio_title": "B2B-exempel värda att skicka för bedömning",
        "cta_title": "Skicka ritning, prov eller specifikation. Vi säger vilket nästa steg som passar.",
        "quote_quick_hint": "Beskriv kort komponenten, serien eller interiördelen och lämna telefon eller e-post. Några konkreta uppgifter räcker för start.",
        "quote_more_hint": "Lägg gärna till företag, antal, plats, deadline eller filer. Det snabbar upp bedömningen men stoppar inte förfrågan.",
        "quote_aside_note": "För B2B-komponenter kan vi diskutera arbete i Polen och Europa. Packning och frakt bedöms efter mått, material och antal.",
        "contact_best_path": "Bästa starten: ritning, prov, foto eller specifikation",
        "contact_best_path_body": "Visa komponenten och användningen istället för att beskriva allt från början. Då bedömer vi passform, risker och saknade uppgifter snabbare.",
    },
    "da": {
        "footer_about": "Snedkeri fra Gościcino for virksomheder, der har brug for trækomponenter, korte serier, POS-/displaydele og projektdetaljer efter tegning, prøve eller specifikation.",
        "footer_quote_body": "Send foto, tegning, prøve eller specifikation. Vi spørger om materiale, antal, finish, deadline, pakning og forsendelse.",
        "trust_region": "Polen og Europa",
        "trust_series": "prøve før serie",
        "trust_specs": "tegninger og specifikationer",
        "trust_custom": "POS, interiørserier og B2B-komponenter",
        "home_paths_title": "Vælg B2B-spor",
        "home_b2b_title": "Har du brug for gentagelige trækomponenter?",
        "home_b2b_body": "Vi kan fremstille prøve, kort serie eller gentageligt parti til virksomheder, der har brug for halvfabrikata i træ, POS-/displaydetaljer eller komponenter til videre montage.",
        "home_b2b_item_photo": "komponenter efter tegning, prøve, foto eller specifikation",
        "home_b2b_item_series": "prøve eller pilotparti før større ordrer",
        "home_b2b_item_coop": "gentagelige elementer til producenter, bureauer og entreprenører",
        "home_b2b_item_shipping": "pakning, afhentning eller forsendelse efter vurdering",
        "home_b2b_cta": "Se B2B-komponentproduktion",
        "process_title": "Fra tegning eller prøve til første parti",
        "portfolio_title": "B2B-eksempler der er værd at sende til vurdering",
        "cta_title": "Send tegning, prøve eller specifikation. Vi siger, hvilket næste skridt der giver mening.",
        "quote_quick_hint": "Beskriv kort komponenten, serien eller interiørdelen og angiv telefon eller e-mail. Få konkrete oplysninger er nok til start.",
        "quote_more_hint": "Tilføj eventuelt virksomhed, antal, placering, deadline eller filer. Det gør vurderingen hurtigere, men stopper ikke forespørgslen.",
        "quote_aside_note": "For B2B-komponenter kan vi drøfte arbejde i Polen og Europa. Pakning og forsendelse vurderes efter mål, materiale og antal.",
        "contact_best_path": "Bedste start: tegning, prøve, foto eller specifikation",
        "contact_best_path_body": "Vis komponenten og brugen i stedet for at beskrive alt fra bunden. Så vurderer vi pasform, risici og manglende data hurtigere.",
    },
    "no": {
        "footer_about": "Snekkerverksted fra Gościcino for bedrifter som trenger trekomponenter, korte serier, POS-/displaydeler og prosjektdetaljer etter tegning, prøve eller spesifikasjon.",
        "footer_quote_body": "Send bilde, tegning, prøve eller spesifikasjon. Vi spør om materiale, antall, overflate, frist, pakking og frakt.",
        "trust_region": "Polen og Europa",
        "trust_series": "prøve før serie",
        "trust_specs": "tegninger og spesifikasjoner",
        "trust_custom": "POS, interiørserier og B2B-komponenter",
        "home_paths_title": "Velg B2B-spor",
        "home_b2b_title": "Trenger du repeterbare trekomponenter?",
        "home_b2b_body": "Vi kan lage prøve, kort serie eller repeterbart parti for bedrifter som trenger halvfabrikata i tre, POS-/displaydetaljer eller komponenter for videre montering.",
        "home_b2b_item_photo": "komponenter etter tegning, prøve, bilde eller spesifikasjon",
        "home_b2b_item_series": "prøve eller pilotparti før større ordre",
        "home_b2b_item_coop": "repeterbare elementer for produsenter, byråer og entreprenører",
        "home_b2b_item_shipping": "pakking, henting eller frakt etter vurdering",
        "home_b2b_cta": "Se B2B-komponentproduksjon",
        "process_title": "Fra tegning eller prøve til første parti",
        "portfolio_title": "B2B-eksempler verdt å sende til vurdering",
        "cta_title": "Send tegning, prøve eller spesifikasjon. Vi sier hvilket neste steg som passer.",
        "quote_quick_hint": "Beskriv kort komponenten, serien eller interiørdelen og legg igjen telefon eller e-post. Noen konkrete opplysninger er nok for start.",
        "quote_more_hint": "Legg gjerne til firma, antall, sted, frist eller filer. Det gjør vurderingen raskere, men stopper ikke forespørselen.",
        "quote_aside_note": "For B2B-komponenter kan vi diskutere arbeid i Polen og Europa. Pakking og frakt vurderes etter mål, materiale og antall.",
        "contact_best_path": "Beste start: tegning, prøve, bilde eller spesifikasjon",
        "contact_best_path_body": "Vis komponenten og bruken i stedet for å beskrive alt fra bunnen. Da vurderer vi passform, risiko og manglende data raskere.",
    },
}

for _code, _updates in FOREIGN_UI_B2B_REFOCUS.items():
    UI_COPY[_code].update(_updates)


FOREIGN_UI_MARKET_REFINEMENT = {
    "en": {
        "footer_about": "A Gościcino workshop producing wooden components, samples, short runs, POS/display parts and fit-out batches for B2B clients in Poland and Europe.",
        "footer_quote_body": "Send a drawing, sample, photo or specification. We will check fit, missing data and the first realistic production step.",
        "home_paths_title": "Choose the right B2B route",
        "home_b2b_title": "Outsource a wooden component without building a joinery line",
        "home_b2b_body": "Use us for the wooden part of the process: sample, pilot batch, repeatable component, POS/display detail or fit-out batch prepared from a clear reference.",
        "home_b2b_item_photo": "drawing, sample, photo or specification as the starting point",
        "home_b2b_item_series": "sample or pilot batch before repeat orders",
        "home_b2b_item_coop": "components for manufacturers, agencies, retailers and contractors",
        "home_b2b_item_shipping": "packing, pickup or shipping assessed before production",
        "process_title": "From reference to a sample or batch decision",
        "portfolio_title": "B2B cases to compare with your brief",
        "cta_title": "Send the component reference. We will tell you whether it fits the workshop and what data is missing.",
        "quote_quick_hint": "Describe the component, batch or fit-out part and leave a phone number or email. A reference photo, drawing or sample can come now or later.",
        "quote_more_hint": "Add company, quantity, country, deadline and files if you have them. These details speed up assessment but are not required to send the inquiry.",
        "quote_aside_note": "For B2B work in Europe, packing and shipping are checked after dimensions, material, finish and quantity are known.",
        "contact_best_path": "Best start: show the component",
        "contact_best_path_body": "A drawing, sample, photo or specification is faster than a long description. It lets us check fit, risks, packing and the missing data for pricing.",
    },
    "de": {
        "footer_about": "Werkstatt aus Gościcino für B2B-Holzelemente, Muster, Kleinserien, POS-/Displayteile und Objektchargen in Polen und Europa.",
        "footer_quote_body": "Senden Sie Zeichnung, Muster, Foto oder Spezifikation. Wir prüfen Passung, fehlende Daten und den ersten realistischen Fertigungsschritt.",
        "home_paths_title": "Den passenden B2B-Einstieg wählen",
        "home_b2b_title": "Holzelement auslagern, ohne eigene Tischlereilinie aufzubauen",
        "home_b2b_body": "Wir übernehmen den Holzteil des Prozesses: Muster, Pilotcharge, wiederholbares Element, POS-/Displaydetail oder Objektcharge nach klarer Referenz.",
        "home_b2b_item_photo": "Zeichnung, Muster, Foto oder Spezifikation als Startpunkt",
        "home_b2b_item_series": "Muster oder Pilotcharge vor wiederholbaren Bestellungen",
        "home_b2b_item_coop": "Elemente für Hersteller, Agenturen, Retail-Teams und Ausbauer",
        "home_b2b_item_shipping": "Verpackung, Abholung oder Versand vor Fertigung prüfen",
        "process_title": "Von der Referenz zur Entscheidung über Muster oder Charge",
        "portfolio_title": "B2B-Cases zum Abgleich mit Ihrer Anfrage",
        "cta_title": "Senden Sie die Referenz zum Element. Wir sagen, ob es zur Werkstatt passt und welche Daten fehlen.",
        "quote_quick_hint": "Beschreiben Sie Element, Serie oder Objektteil und hinterlassen Sie Telefon oder E-Mail. Referenzfoto, Zeichnung oder Muster können jetzt oder später folgen.",
        "quote_more_hint": "Ergänzen Sie Firma, Menge, Land, Termin und Dateien, wenn vorhanden. Das beschleunigt die Prüfung, ist aber nicht nötig, um die Anfrage zu senden.",
        "quote_aside_note": "Für B2B-Arbeit in Europa prüfen wir Verpackung und Versand nach Maßen, Material, Oberfläche und Menge.",
        "contact_best_path": "Bester Start: Element zeigen",
        "contact_best_path_body": "Zeichnung, Muster, Foto oder Spezifikation sind schneller als lange Beschreibungen. So prüfen wir Passung, Risiken, Verpackung und fehlende Daten für die Kalkulation.",
    },
    "sv": {
        "footer_about": "Verkstad i Gościcino för B2B-träkomponenter, prover, korta serier, POS-/displaydelar och inredningsbatcher i Polen och Europa.",
        "footer_quote_body": "Skicka ritning, prov, foto eller specifikation. Vi bedömer passform, saknade uppgifter och första realistiska produktionssteg.",
        "home_paths_title": "Välj rätt B2B-spår",
        "home_b2b_title": "Lägg ut träkomponenten utan egen snickerikapacitet",
        "home_b2b_body": "Vi tar hand om träledet i processen: prov, pilotbatch, återkommande komponent, POS-/displaydetalj eller inredningsbatch från en tydlig referens.",
        "home_b2b_item_photo": "ritning, prov, foto eller specifikation som startpunkt",
        "home_b2b_item_series": "prov eller pilotbatch före återkommande beställningar",
        "home_b2b_item_coop": "komponenter för producenter, byråer, displayteam och entreprenörer",
        "home_b2b_item_shipping": "packning, upphämtning eller frakt bedöms före produktion",
        "process_title": "Från referens till beslut om prov eller batch",
        "portfolio_title": "B2B-case att jämföra med er brief",
        "cta_title": "Skicka komponentens referens. Vi säger om den passar verkstaden och vilka uppgifter som saknas.",
        "quote_quick_hint": "Beskriv komponenten, batchen eller inredningsdelen och lämna telefon eller e-post. Referensfoto, ritning eller prov kan komma nu eller senare.",
        "quote_more_hint": "Lägg till företag, antal, land, deadline och filer om du har dem. Det snabbar upp bedömningen men krävs inte för att skicka förfrågan.",
        "quote_aside_note": "För B2B-arbete i Europa bedöms packning och frakt efter mått, material, finish och antal.",
        "contact_best_path": "Bästa start: visa komponenten",
        "contact_best_path_body": "Ritning, prov, foto eller specifikation går snabbare än en lång beskrivning. Då bedömer vi passform, risker, packning och saknade uppgifter för pris.",
    },
    "da": {
        "footer_about": "Værksted i Gościcino for B2B-trækomponenter, prøver, korte serier, POS-/displaydele og interiørpartier i Polen og Europa.",
        "footer_quote_body": "Send tegning, prøve, foto eller specifikation. Vi vurderer pasform, manglende data og første realistiske produktionsskridt.",
        "home_paths_title": "Vælg det rigtige B2B-spor",
        "home_b2b_title": "Outsource trækomponenten uden egen snedkerkapacitet",
        "home_b2b_body": "Vi tager os af trædelen i processen: prøve, pilotparti, gentagelig komponent, POS-/displaydetalje eller interiørparti ud fra en klar reference.",
        "home_b2b_item_photo": "tegning, prøve, foto eller specifikation som startpunkt",
        "home_b2b_item_series": "prøve eller pilotparti før gentagelige ordrer",
        "home_b2b_item_coop": "komponenter til producenter, bureauer, displayteams og entreprenører",
        "home_b2b_item_shipping": "pakning, afhentning eller forsendelse vurderes før produktion",
        "process_title": "Fra reference til beslutning om prøve eller parti",
        "portfolio_title": "B2B-cases til sammenligning med jeres brief",
        "cta_title": "Send komponentens reference. Vi siger, om den passer til værkstedet, og hvilke data der mangler.",
        "quote_quick_hint": "Beskriv komponenten, partiet eller interiørdelen og angiv telefon eller e-mail. Referencefoto, tegning eller prøve kan komme nu eller senere.",
        "quote_more_hint": "Tilføj virksomhed, antal, land, deadline og filer, hvis du har dem. Det gør vurderingen hurtigere, men er ikke nødvendigt for at sende forespørgslen.",
        "quote_aside_note": "For B2B-arbejde i Europa vurderes pakning og forsendelse efter mål, materiale, finish og antal.",
        "contact_best_path": "Bedste start: vis komponenten",
        "contact_best_path_body": "Tegning, prøve, foto eller specifikation er hurtigere end en lang beskrivelse. Så vurderer vi pasform, risici, pakning og manglende data for pris.",
    },
    "no": {
        "footer_about": "Verksted i Gościcino for B2B-trekomponenter, prøver, korte serier, POS-/displaydeler og interiørpartier i Polen og Europa.",
        "footer_quote_body": "Send tegning, prøve, bilde eller spesifikasjon. Vi vurderer passform, manglende data og første realistiske produksjonssteg.",
        "home_paths_title": "Velg riktig B2B-spor",
        "home_b2b_title": "Sett bort trekomponenten uten egen snekkerkapasitet",
        "home_b2b_body": "Vi tar hånd om treleddet i prosessen: prøve, pilotparti, repeterbar komponent, POS-/displaydetalj eller interiørparti fra en tydelig referanse.",
        "home_b2b_item_photo": "tegning, prøve, bilde eller spesifikasjon som startpunkt",
        "home_b2b_item_series": "prøve eller pilotparti før repeterbare ordre",
        "home_b2b_item_coop": "komponenter for produsenter, byråer, displayteam og entreprenører",
        "home_b2b_item_shipping": "pakking, henting eller frakt vurderes før produksjon",
        "process_title": "Fra referanse til beslutning om prøve eller parti",
        "portfolio_title": "B2B-cases å sammenligne med briefen",
        "cta_title": "Send komponentreferansen. Vi sier om den passer verkstedet og hvilke data som mangler.",
        "quote_quick_hint": "Beskriv komponenten, partiet eller interiørdelen og legg igjen telefon eller e-post. Referansebilde, tegning eller prøve kan komme nå eller senere.",
        "quote_more_hint": "Legg til firma, antall, land, frist og filer hvis du har dem. Det gjør vurderingen raskere, men er ikke nødvendig for å sende forespørselen.",
        "quote_aside_note": "For B2B-arbeid i Europa vurderes pakking og frakt etter mål, materiale, overflate og antall.",
        "contact_best_path": "Beste start: vis komponenten",
        "contact_best_path_body": "Tegning, prøve, bilde eller spesifikasjon er raskere enn en lang beskrivelse. Da vurderer vi passform, risiko, pakking og manglende data for pris.",
    },
}

for _code, _updates in FOREIGN_UI_MARKET_REFINEMENT.items():
    UI_COPY[_code].update(_updates)

for _code, _copy in UI_COPY.items():
    _copy.setdefault("menu_label", _MENU_LABELS.get(_code, "Menu"))
    _copy.update(_QUOTE_FILE_PROMPTS.get(_code, _QUOTE_FILE_PROMPTS["en"]))


def get_ui_copy(language_code):
    normalized = (language_code or "pl").split("-")[0]
    return UI_COPY.get(normalized, UI_COPY["pl"])
