upstream kajax {
  ip_hash;
  server unix:/projects/kajax/nginx/kajax.sock fail_timeout=0;
}

server {
    listen 80;
    keepalive_timeout 100;
    server_name kajax.eu;
    root /src/static;
    client_max_body_size 100m;
    # block most common botnet used urls
    location /cgi-bin {
        return 403;
    }
    location /media {
        alias   /projects/kajax/data/public/media;
        expires 1h;
    }
    location /static {
        alias   /projects/kajax/data/public/static;
        expires 1h;
    }
    location / {
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
        proxy_redirect off;
        proxy_pass http://kajax/;
    }

}
server {
    server_name www.kajax.eu;
    return 301 $scheme://kajax.eu$request_uri;
}