# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-12 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sliderimage',
            name='button_text',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='sliderimage',
            name='button_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sliderimage',
            name='tags',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
