# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-13 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20160612_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='subject',
            field=models.CharField(default='None', max_length=128),
            preserve_default=False,
        ),
    ]
