FORM_COPY = {
    "pl": {
        "name": "Imię",
        "email": "Email",
        "phone": "Telefon",
        "company": "Firma",
        "inquiry_type": "Czego dotyczy temat?",
        "scale": "Ilość / skala",
        "location": "Lokalizacja",
        "expected_timing": "Termin",
        "message": "Krótko opisz, co mamy wykonać",
        "attachments": "Zdjęcia, rysunki lub specyfikacja",
        "consent": "Wyrażam zgodę na kontakt w sprawie przesłanego zapytania.",
        "company_help": "Opcjonalnie, jeśli piszesz jako firma, producent, architekt lub wykonawca.",
        "location_help": "Dla B2B wpisz kraj/miasto. Dla stolarki budowlanej wpisz miejscowość inwestycji.",
        "expected_timing_help": "Np. prototyp w czerwcu, realizacja po wakacjach, stałe partie co miesiąc.",
        "message_help": "Wystarczy krótki opis. Jeśli masz rysunek lub zdjęcie, dodaj je w sekcji więcej informacji.",
        "attachments_help": "Opcjonalnie. Zdjęcia i PDF-y bardzo przyspieszają pierwszą ocenę.",
        "contact_required": "Podaj telefon albo email, żebyśmy mogli wrócić z odpowiedzią.",
        "success_message": "Dziękujemy. Zapytanie zostało zapisane i wrócimy z odpowiedzią po analizie projektu.",
        "b2b_components": "Elementy drewniane B2B",
        "construction_joinery": "Stolarka budowlana",
        "custom_artistic": "Custom / stolarstwo artystyczne",
        "other": "Inne",
        "one_piece": "1 sztuka",
        "small_series": "Mała seria",
        "recurring": "Stała współpraca",
        "unknown": "Nie wiem jeszcze",
    },
    "en": {
        "name": "Name",
        "email": "Email",
        "phone": "Phone",
        "company": "Company",
        "inquiry_type": "What is the project about?",
        "scale": "Quantity / scale",
        "location": "Location",
        "expected_timing": "Timing",
        "message": "Briefly describe what you need made",
        "attachments": "Photos, drawings or specification",
        "consent": "I agree to be contacted about this inquiry.",
        "company_help": "Optional, if you are writing as a company, manufacturer, architect or contractor.",
        "location_help": "For B2B, enter country/city. For installed joinery, enter the project location.",
        "expected_timing_help": "For example: prototype in June, after summer, recurring monthly batches.",
        "message_help": "A short description is enough. If you have a drawing or photo, add it under more information.",
        "attachments_help": "Optional. Photos and PDFs make the first assessment much faster.",
        "contact_required": "Please provide a phone number or email so we can reply.",
        "success_message": "Thank you. Your inquiry has been saved and we will reply after reviewing the project.",
        "b2b_components": "B2B wooden components",
        "construction_joinery": "Construction joinery",
        "custom_artistic": "Custom / artistic woodwork",
        "other": "Other",
        "one_piece": "One piece",
        "small_series": "Small batch",
        "recurring": "Recurring cooperation",
        "unknown": "Not sure yet",
    },
    "de": {
        "name": "Name",
        "email": "E-Mail",
        "phone": "Telefon",
        "company": "Firma",
        "inquiry_type": "Worum geht es?",
        "scale": "Menge / Umfang",
        "location": "Standort",
        "expected_timing": "Zeitrahmen",
        "message": "Beschreiben Sie kurz, was gefertigt werden soll",
        "attachments": "Fotos, Zeichnungen oder Spezifikation",
        "consent": "Ich bin mit der Kontaktaufnahme zu dieser Anfrage einverstanden.",
        "company_help": "Optional, wenn Sie als Firma, Hersteller, Architekt oder Auftragnehmer schreiben.",
        "location_help": "Für B2B bitte Land/Stadt angeben. Für montierte Tischlerarbeiten den Projektort.",
        "expected_timing_help": "Zum Beispiel: Prototyp im Juni, nach dem Sommer, monatliche Serien.",
        "message_help": "Eine kurze Beschreibung reicht. Zeichnung oder Foto können Sie unter weitere Informationen hinzufügen.",
        "attachments_help": "Optional. Fotos und PDFs beschleunigen die erste Einschätzung deutlich.",
        "contact_required": "Bitte geben Sie Telefon oder E-Mail an, damit wir antworten können.",
        "success_message": "Vielen Dank. Ihre Anfrage wurde gespeichert und wir melden uns nach Prüfung des Projekts.",
        "b2b_components": "B2B-Holzelemente",
        "construction_joinery": "Bauschreinerei",
        "custom_artistic": "Sonderanfertigung / Kunsthandwerk",
        "other": "Andere Anfrage",
        "one_piece": "Einzelstück",
        "small_series": "Kleinserie",
        "recurring": "Regelmäßige Zusammenarbeit",
        "unknown": "Noch nicht sicher",
    },
    "sv": {
        "name": "Namn",
        "email": "E-post",
        "phone": "Telefon",
        "company": "Företag",
        "inquiry_type": "Vad gäller projektet?",
        "scale": "Antal / omfattning",
        "location": "Plats",
        "expected_timing": "Tidplan",
        "message": "Beskriv kort vad du behöver få tillverkat",
        "attachments": "Foton, ritningar eller specifikation",
        "consent": "Jag samtycker till kontakt om denna förfrågan.",
        "company_help": "Valfritt, om du skriver som företag, tillverkare, arkitekt eller entreprenör.",
        "location_help": "För B2B: ange land/stad. För monterat snickeri: ange projektplats.",
        "expected_timing_help": "Till exempel: prototyp i juni, efter sommaren, återkommande månadsserier.",
        "message_help": "En kort beskrivning räcker. Har du ritning eller foto kan du lägga till det under mer information.",
        "attachments_help": "Valfritt. Foton och PDF:er gör första bedömningen mycket snabbare.",
        "contact_required": "Ange telefon eller e-post så att vi kan återkomma.",
        "success_message": "Tack. Din förfrågan har sparats och vi återkommer efter att ha granskat projektet.",
        "b2b_components": "B2B-träkomponenter",
        "construction_joinery": "Byggsnickeri",
        "custom_artistic": "Special / konstnärligt träarbete",
        "other": "Annat",
        "one_piece": "En del",
        "small_series": "Kort serie",
        "recurring": "Återkommande samarbete",
        "unknown": "Inte säker än",
    },
    "da": {
        "name": "Navn",
        "email": "E-mail",
        "phone": "Telefon",
        "company": "Virksomhed",
        "inquiry_type": "Hvad handler projektet om?",
        "scale": "Antal / omfang",
        "location": "Placering",
        "expected_timing": "Tidsplan",
        "message": "Beskriv kort, hvad der skal fremstilles",
        "attachments": "Fotos, tegninger eller specifikation",
        "consent": "Jeg accepterer at blive kontaktet om denne forespørgsel.",
        "company_help": "Valgfrit, hvis du skriver som virksomhed, producent, arkitekt eller entreprenør.",
        "location_help": "For B2B: angiv land/by. For monteret snedkerarbejde: angiv projektets placering.",
        "expected_timing_help": "For eksempel: prototype i juni, efter sommeren, faste månedlige serier.",
        "message_help": "En kort beskrivelse er nok. Har du tegning eller foto, kan du tilføje det under flere oplysninger.",
        "attachments_help": "Valgfrit. Fotos og PDF'er gør den første vurdering meget hurtigere.",
        "contact_required": "Angiv telefon eller e-mail, så vi kan svare.",
        "success_message": "Tak. Din forespørgsel er gemt, og vi vender tilbage efter gennemgang af projektet.",
        "b2b_components": "B2B-trækomponenter",
        "construction_joinery": "Byggesnedkeri",
        "custom_artistic": "Special / kunstnerisk træarbejde",
        "other": "Andet",
        "one_piece": "Ét stykke",
        "small_series": "Kort serie",
        "recurring": "Løbende samarbejde",
        "unknown": "Ikke sikker endnu",
    },
    "no": {
        "name": "Navn",
        "email": "E-post",
        "phone": "Telefon",
        "company": "Firma",
        "inquiry_type": "Hva gjelder prosjektet?",
        "scale": "Antall / omfang",
        "location": "Sted",
        "expected_timing": "Tidsplan",
        "message": "Beskriv kort hva som skal lages",
        "attachments": "Bilder, tegninger eller spesifikasjon",
        "consent": "Jeg samtykker til å bli kontaktet om denne forespørselen.",
        "company_help": "Valgfritt, hvis du skriver som firma, produsent, arkitekt eller entreprenør.",
        "location_help": "For B2B: oppgi land/by. For montert snekkerarbeid: oppgi prosjektsted.",
        "expected_timing_help": "For eksempel: prototype i juni, etter sommeren, faste månedlige serier.",
        "message_help": "En kort beskrivelse holder. Har du tegning eller bilde, legg det til under mer informasjon.",
        "attachments_help": "Valgfritt. Bilder og PDF-er gjør første vurdering mye raskere.",
        "contact_required": "Oppgi telefon eller e-post slik at vi kan svare.",
        "success_message": "Takk. Forespørselen er lagret, og vi kommer tilbake etter å ha vurdert prosjektet.",
        "b2b_components": "B2B-trekomponenter",
        "construction_joinery": "Byggsnekkerarbeid",
        "custom_artistic": "Spesial / kunstnerisk trearbeid",
        "other": "Annet",
        "one_piece": "Én del",
        "small_series": "Kort serie",
        "recurring": "Fast samarbeid",
        "unknown": "Ikke sikker ennå",
    },
}


def get_form_copy(language_code):
    normalized = (language_code or "pl").split("-")[0]
    return FORM_COPY.get(normalized, FORM_COPY["pl"])
