FORM_COPY = {
    "pl": {
        "name": "Imię",
        "email": "Email",
        "phone": "Telefon",
        "company": "Firma",
        "inquiry_type": "Co mamy wykonać?",
        "scale": "Liczba sztuk",
        "location": "Lokalizacja",
        "expected_timing": "Termin",
        "message": "Opisz element lub zakres prac",
        "attachments": "Zdjęcie, rysunek albo wzór",
        "consent": "Wyrażam zgodę na kontakt w sprawie przesłanego zapytania.",
        "company_help": "Opcjonalnie, jeśli piszesz z firmy.",
        "location_help": "Przy montażu wpisz miejscowość. Przy elementach dla firm wystarczy kraj lub miasto.",
        "expected_timing_help": "Np. próbka w czerwcu, montaż po wakacjach, partie co miesiąc.",
        "message_help": "Wystarczy kilka konkretów: co to ma być, do czego służy, ile sztuk i co ma być ważne w efekcie końcowym.",
        "attachments_help": "Opcjonalnie. Jedno dobre zdjęcie, rysunek albo wzór często wystarczy, żeby zacząć rozmowę.",
        "contact_required": "Podaj telefon albo email, żebyśmy mogli wrócić z odpowiedzią.",
        "success_message": "Dziękujemy. Zapytanie dotarło. Sprawdzimy opis i wrócimy z odpowiedzią albo konkretnymi pytaniami. Jeśli pojawi się dodatkowe zdjęcie, rysunek lub wymiar, możesz odpisać na maila z potwierdzeniem.",
        "b2b_components": "Elementy drewniane dla firmy",
        "construction_joinery": "Schody, drzwi lub zabudowa",
        "custom_artistic": "Nietypowy detal / projekt indywidualny",
        "other": "Inne",
        "one_piece": "Pojedynczy element",
        "small_series": "Próbka lub mała seria",
        "recurring": "Kolejne partie",
        "unknown": "Nie wiem jeszcze",
    },
    "en": {
        "name": "Name",
        "email": "Email",
        "phone": "Phone",
        "company": "Company",
        "inquiry_type": "What is the project about?",
        "scale": "Quantity / scale",
        "location": "Location",
        "expected_timing": "Timing",
        "message": "Briefly describe what you need made",
        "attachments": "Photos, drawings or specification",
        "consent": "I agree to be contacted about this inquiry.",
        "company_help": "Optional, if you are writing as a company, manufacturer, architect, agency or contractor.",
        "location_help": "For B2B, enter country/city. For installed joinery, enter the project or installation location.",
        "expected_timing_help": "For example: sample in June, after summer, recurring monthly batches.",
        "message_help": "A few concrete sentences are enough: what it is, what it is for, how many pieces and which effect matters.",
        "attachments_help": "Optional. Photos, drawings and PDFs make the first assessment much faster.",
        "contact_required": "Please provide a phone number or email so we can reply.",
        "success_message": "Thank you. Your inquiry has been saved. We will review the scope and let you know what information is needed for the next pricing step.",
        "b2b_components": "B2B wooden components",
        "construction_joinery": "Construction joinery",
        "custom_artistic": "Unusual details",
        "other": "Other",
        "one_piece": "One piece",
        "small_series": "Small batch",
        "recurring": "Recurring cooperation",
        "unknown": "Not sure yet",
    },
    "de": {
        "name": "Name",
        "email": "E-Mail",
        "phone": "Telefon",
        "company": "Firma",
        "inquiry_type": "Worum geht es?",
        "scale": "Menge / Umfang",
        "location": "Standort",
        "expected_timing": "Zeitrahmen",
        "message": "Beschreiben Sie kurz, was gefertigt werden soll",
        "attachments": "Fotos, Zeichnungen oder Spezifikation",
        "consent": "Ich bin mit der Kontaktaufnahme zu dieser Anfrage einverstanden.",
        "company_help": "Optional, wenn Sie als Firma, Hersteller, Architekt, Agentur oder Auftragnehmer schreiben.",
        "location_help": "Für B2B bitte Land/Stadt angeben. Für montierte Schreinerarbeiten den Projekt- oder Montageort.",
        "expected_timing_help": "Zum Beispiel: Muster im Juni, nach dem Sommer, monatliche Serien.",
        "message_help": "Einige konkrete Sätze reichen: was es ist, wofür es dient, welche Menge und welcher Effekt wichtig ist.",
        "attachments_help": "Optional. Fotos, Zeichnungen und PDFs beschleunigen die erste Einschätzung deutlich.",
        "contact_required": "Bitte geben Sie Telefon oder E-Mail an, damit wir antworten können.",
        "success_message": "Vielen Dank. Ihre Anfrage wurde gespeichert. Wir prüfen den Umfang und melden uns mit den Informationen, die für den nächsten Schritt der Preisfindung nötig sind.",
        "b2b_components": "B2B-Holzelemente",
        "construction_joinery": "Bauschreinerei",
        "custom_artistic": "Sonderanfertigung / ungewöhnliche Details",
        "other": "Andere Anfrage",
        "one_piece": "Einzelstück",
        "small_series": "Kleinserie",
        "recurring": "Regelmäßige Zusammenarbeit",
        "unknown": "Noch nicht sicher",
    },
    "sv": {
        "name": "Namn",
        "email": "E-post",
        "phone": "Telefon",
        "company": "Företag",
        "inquiry_type": "Vad gäller projektet?",
        "scale": "Antal / omfattning",
        "location": "Plats",
        "expected_timing": "Tidplan",
        "message": "Beskriv kort vad du behöver få tillverkat",
        "attachments": "Foton, ritningar eller specifikation",
        "consent": "Jag samtycker till kontakt om denna förfrågan.",
        "company_help": "Valfritt, om du skriver som företag, tillverkare, arkitekt, byrå eller entreprenör.",
        "location_help": "För B2B: ange land/stad. För monterat snickeri: ange projekt- eller montageplats.",
        "expected_timing_help": "Till exempel: prov i juni, efter sommaren, återkommande månadsserier.",
        "message_help": "Några konkreta meningar räcker: vad det är, vad det ska användas till, antal och vilken effekt som är viktig.",
        "attachments_help": "Valfritt. Foton, ritningar och PDF:er gör första bedömningen mycket snabbare.",
        "contact_required": "Ange telefon eller e-post så att vi kan återkomma.",
        "success_message": "Tack. Din förfrågan har sparats. Vi granskar omfattningen och återkommer med vilken information som behövs för nästa offertsteg.",
        "b2b_components": "B2B-träkomponenter",
        "construction_joinery": "Byggsnickeri",
        "custom_artistic": "Special / ovanliga detaljer",
        "other": "Annat",
        "one_piece": "En del",
        "small_series": "Kort serie",
        "recurring": "Återkommande samarbete",
        "unknown": "Inte säker än",
    },
    "da": {
        "name": "Navn",
        "email": "E-mail",
        "phone": "Telefon",
        "company": "Virksomhed",
        "inquiry_type": "Hvad handler projektet om?",
        "scale": "Antal / omfang",
        "location": "Placering",
        "expected_timing": "Tidsplan",
        "message": "Beskriv kort, hvad der skal fremstilles",
        "attachments": "Fotos, tegninger eller specifikation",
        "consent": "Jeg accepterer at blive kontaktet om denne forespørgsel.",
        "company_help": "Valgfrit, hvis du skriver som virksomhed, producent, arkitekt, bureau eller entreprenør.",
        "location_help": "For B2B: angiv land/by. For monteret snedkerarbejde: angiv projekt- eller montagested.",
        "expected_timing_help": "For eksempel: prøve i juni, efter sommeren, faste månedlige serier.",
        "message_help": "Få konkrete sætninger er nok: hvad det er, hvad det skal bruges til, antal og hvilken effekt der er vigtig.",
        "attachments_help": "Valgfrit. Fotos, tegninger og PDF'er gør den første vurdering meget hurtigere.",
        "contact_required": "Angiv telefon eller e-mail, så vi kan svare.",
        "success_message": "Tak. Din forespørgsel er gemt. Vi gennemgår omfanget og vender tilbage med, hvilke oplysninger der er nødvendige til næste tilbudsskridt.",
        "b2b_components": "B2B-trækomponenter",
        "construction_joinery": "Byggesnedkeri",
        "custom_artistic": "Special / usædvanlige detaljer",
        "other": "Andet",
        "one_piece": "Ét stykke",
        "small_series": "Kort serie",
        "recurring": "Løbende samarbejde",
        "unknown": "Ikke sikker endnu",
    },
    "no": {
        "name": "Navn",
        "email": "E-post",
        "phone": "Telefon",
        "company": "Firma",
        "inquiry_type": "Hva gjelder prosjektet?",
        "scale": "Antall / omfang",
        "location": "Sted",
        "expected_timing": "Tidsplan",
        "message": "Beskriv kort hva som skal lages",
        "attachments": "Bilder, tegninger eller spesifikasjon",
        "consent": "Jeg samtykker til å bli kontaktet om denne forespørselen.",
        "company_help": "Valgfritt, hvis du skriver som firma, produsent, arkitekt, byrå eller entreprenør.",
        "location_help": "For B2B: oppgi land/by. For montert snekkerarbeid: oppgi prosjekt- eller monteringssted.",
        "expected_timing_help": "For eksempel: prøve i juni, etter sommeren, faste månedlige serier.",
        "message_help": "Noen konkrete setninger holder: hva det er, hva det skal brukes til, antall og hvilken effekt som er viktig.",
        "attachments_help": "Valgfritt. Bilder, tegninger og PDF-er gjør første vurdering mye raskere.",
        "contact_required": "Oppgi telefon eller e-post slik at vi kan svare.",
        "success_message": "Takk. Forespørselen er lagret. Vi vurderer omfanget og kommer tilbake med hvilken informasjon som trengs for neste prissteg.",
        "b2b_components": "B2B-trekomponenter",
        "construction_joinery": "Byggsnekkerarbeid",
        "custom_artistic": "Spesial / uvanlige detaljer",
        "other": "Annet",
        "one_piece": "Én del",
        "small_series": "Kort serie",
        "recurring": "Fast samarbeid",
        "unknown": "Ikke sikker ennå",
    },
}


def get_form_copy(language_code):
    normalized = (language_code or "pl").split("-")[0]
    return FORM_COPY.get(normalized, FORM_COPY["pl"])
